### ISSUE TITLE
Support `run_return` on macos

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1005]
Currently the macOS target platform does not support the `run_return` method of the desktop event loop extension. Since I haven't been able to find the time to look into this myself, I've decided to create this issue to track it.

This is currently the biggest thing still missing from the event loop 2 rework as far as Alacritty is concerned. The `run_return` method is mainly required for its lifetime, allowing to run it without having a 'static constraint for the event handler. So I don't think just adding a 'static bound to the `run_return` trait and calling the `run` method is an option.

**Comment by XVilka** [comment]
Are there any updates on this?

**Comment by Osspial** [comment]
@XVilka Not that I'm aware of. From what I've seen skimming the macOS code this shouldn't be too hard to implement, but I'm not familiar with the semantics of that backend and I don't know if there are any hidden gotchas with the naive solution.

**Comment by chrisduerr** [comment]
> From what I've seen skimming the macOS code this shouldn't be too hard to implement

I'd be curious what makes you say that. I've looked at the macOS code and it looks to me like it would require a major rework to implement this.

Currently the callback for `run` is stored globally in a static variable, so it's not possible to implement `run_return` because of the lifetime guarantees, so we can't make that static since it needs to return the values moved into the closure.

That's the main reason why I haven't looked at it yet, since it seems like it requires significant work to get done and I just do not have that time at the moment.

**Comment by Osspial** [comment]
> Currently the callback for `run` is stored globally in a static variable, so it's not possible to implement `run_return` because of the lifetime guarantees, so we can't make that static since it needs to return the values moved into the closure.

Can't we use `transmute` to artificially extend the closure's lifetime ([this is explicitly supported behavior](https://doc.rust-lang.org/std/mem/fn.transmute.html#examples)), and then unset the global closure at the end of `run_return`?

**Comment by chrisduerr** [comment]
> Can't we use transmute to artificially extend the closure's lifetime (this is explicitly supported behavior), and then unset the global closure at the end of run_return?

Honestly in my opinion that sounds like very unidiomatic Rust code that would be very prone for serious issues. Sure `transmute` can do that, but it's also marked as `unsafe` for a very good reason.

I'm not sure *why* the macOS code was written the way it is. But at that point I feel like we'd have C code, not Rust code. A static global reference to a function which requires to be manually freed is much closer to what you'd do in C than Rust in my experience.

**Comment by Osspial** [comment]
@chrisduerr Those are all valid points, but I don't think they make it any less valid as a solution. Yes, you have to be extremely careful with `unsafe` code to make sure it upholds Rust's contracts, but it's still an extremely useful tool to have and I believe is the correct approach here.

Also, it's worth noting that the `transmute` trick would probably be necessary for most reasonable approaches for structuring macOS's backend, since the callback data needs to be associated with the `Window` types and `Window`s can be created before the callback is created. That isn't just conjecture - the Windows API has a similarish design, and we need to use lifetime transmutes there (relevant code [here](https://github.com/rust-windowing/winit/blob/73cf10e4f361a854f4f16ada31b1c391e7ec6846/src/platform_impl/windows/event_loop.rs#L176-L180), [here](https://github.com/rust-windowing/winit/blob/73cf10e4f361a854f4f16ada31b1c391e7ec6846/src/platform_impl/windows/event_loop.rs#L250), and [here](https://github.com/rust-windowing/winit/blob/73cf10e4f361a854f4f16ada31b1c391e7ec6846/src/platform_impl/windows/event_loop.rs#L334-L355)) to get the callback working even though the Windows backend doesn't use shared global state.

The one thing I'd be concerned about is whether it's possible to violate safety guarantees by creating multiple `EventLoop`s, but honestly I still have that concern today with the current state of the codebase.

**Comment by chrisduerr** [comment]
> since the callback data needs to be associated with the Window types and Windows can be created before the callback is created

What stops you from just storing the callback on the window structures and having it as `None` until it's defined?

I just don't think there's usually a good reason to do things this way if you want to make sure that it's only initialized when `run_return` is called and directly freed once it returns. If that's the case, it seems like you actually do want the normal lifetime guarantees of Rust, but you just want to have the option of not having a callback registered.

But I have no clue about the internals of winit, it's not up to me at all. It's just a bit of a code smell as far as I can tell. Though I would expect this to be a limitation for getting contributors to work on this.

**Comment by Osspial** [comment]
> What stops you from just storing the callback on the window structures and having it as `None` until it's defined?

The compiler isn't smart enough to realize that that's safe. [This example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d4c7768133c11fa8b0cd95a04b2aebef) roughly mirrors the event loop structure you're suggesting, and the compiler rejects it even though we aren't causing invalid behavior.

> I just don't think there's usually a good reason to do things this way if you want to make sure that it's only initialized when `run_return` is called and directly freed once it returns. If that's the case, it seems like you actually do want the normal lifetime guarantees of Rust, but you just want to have the option of not having a callback registered.

I'll argue that the lack of any other good solution is reason enough. If someone manages to come up with a solution that doesn't involve this or other unsafe code I'd be interested, but I'm fairly certain it's impossible to support without invoking unsafe code internally. That's okay. Safe Rust is built on top of unsafe Rust, and we're invoking this in a well-controlled scenario that should not result in memory safety violations. I don't see the point of holding up this feature while waiting for a theoretically cleaner solution that may or may not exist, while we already have a solution that's demonstrated to work on Windows.
