### ISSUE TITLE
Window is showing white screen on all example launch, not redrawing until a click somewhere.

### ISSUE THREAD

**Issue by serak** [rust-windowing/winit#1012]
i am getting a blank white window on cargo run --example window and actually i have tried all of the examples and its the same. unless i click somewhere on the window nothing is getting displayed

My OS 
- Windows 10 1903
- Rust 1.36 Stable
![Annotation 2019-07-05 132127](https://user-images.githubusercontent.com/3592372/60717170-ce972c00-9f29-11e9-9afa-d0674012f25c.png)

**Comment by ZeGentzy** [comment]
Can you try this against winit's master?

cc @Osspial

**Comment by ZeGentzy** [comment]
related: #987 #995 #994

**Comment by serak** [comment]
yap i updated glutin_examples cargo.toml file to this but same issue

[dependencies]
glutin = { path = "../glutin" }
winit = { git = "https://github.com/rust-windowing/winit" }
takeable-option = "0.4"
image = "0.21"

**Comment by Osspial** [comment]
This is happening because the Glutin examples wait for a `RedrawRequested` event to do their redrawing, but a `RedrawRequested` event doesn't automatically get generated when the window is created.

Fixing this should be easy - we just need to call `request_redraw` in the `Window::new`/`WindowBuilder::build` functions.

**Comment by sumit0190** [comment]
Hmm...I tried out the fix suggested by @Osspial a few days ago when I first ran across this issue, and it didn't seem to work then. Maybe I implemented it incorrectly - I added a call to `request_redraw` in the closure that creates the `Window` object to be returned in `WindowBuilder::build`. Since it was clearly not working I even tried placing a breakpoint in my `request_redraw` method, which surprisingly wasn't hit. 

I'll check it out again later today.

**Comment by ZeGentzy** [comment]
@Osspial That is unfortunate. Shouldn't a redraw event be generated at the start?

**Comment by Osspial** [comment]
@ZeGentzy Yep. I think we just overlooked that when implementing most of the backends.

**Comment by Osspial** [comment]
@sumit0190 What platform are you running on? It works for me on Windows, but some platforms might not be handling `request_redraw` properly if it's called before the event loop starts.

**Comment by sumit0190** [comment]
@Osspial Sorry for the late response: yes I did test it on Windows 10 with no success. I probably bungled it up somehow, I'll try it again ASAP.
