### ISSUE TITLE
Values moved into run closure not having `drop` called

### ISSUE THREAD

**Issue by KeyMaster-** [rust-windowing/winit#1058]
It appears that values moved into the closure provided to `run` don't get `drop` called when the event loop terminates
The example below shows a minimal example. The `droppable` is moved into the closure and used, but when I close the window, I don't see a "Dropping." message being printed indicating that the value has been dropped as the program terminates.
In contrast, the scope at the start of main shows that in a usual scope, `drop` gets called correctly.

I may be misunderstanding some of the expected behaviour of drop though, if so I'd appreciate a clarification on this.

Example: (tested on winit 0.20.0-alpha2, MacOS 10.14.4)
```rust
use winit::{
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  window::WindowBuilder
};

struct Droppable {
  x: i32
}

impl Drop for Droppable {
  fn drop(&mut self) {
    println!("Dropping.");
  }
}

fn main() {
  {
    let _test_droppable = Droppable { x: 7 };
  }

  let event_loop = EventLoop::new();
  let _window = WindowBuilder::new().build(&event_loop).unwrap();

  let droppable = Droppable {
    x: 7
  };

  event_loop.run(move |event, _, control_flow| {
    println!("x is {}", droppable.x);
    match event {
      Event::WindowEvent  {
        event: WindowEvent::CloseRequested,
        ..
      } => *control_flow = ControlFlow::Exit,
      _ => *control_flow = ControlFlow::Wait,
    }
  });
}
```

**Comment by Osspial** [comment]
I can confirm that this is a bug on macOS - on Windows, running the example you've included properly drops `droppable` at the end of the event loop's execution.

It looks like the cause is that we aren't explicitly dropping the closure in [`AppState::exit`](https://github.com/rust-windowing/winit/blob/39e668ffb0a1437305508aaa155a57f354b5aa24/src/platform_impl/macos/app_state.rs#L195-L199). Fixing this should just be a matter of inserting that call.

**Comment by KeyMaster-** [comment]
Just added that, and it seems to work with my test case. PR'd it at #1063, lmk if there's any further changes needed.
