### ISSUE TITLE
send_event: Why?

### ISSUE THREAD

**Issue by cheako** [rust-windowing/winit#1060]
What's the rational behind having user events?  Why wouldn't an app just run whatever code needing to be run?

**Comment by felixrabe** [comment]
In my understanding, it helps with implementing asynchronous actions.

**Comment by KeyMaster-** [comment]
I just used them, so I can give a concrete example:
My main thread handles most program logic and rendering. To save CPU it uses `ControlFlow::Wait` to be put to sleep until new events arrive that may need processing (e.g. user input).
My app loads large images, which can take a while (>1 second), so I do that on separate threads, because otherwise the app would just hang while the load happens The loader thread loads the image, then sends the data over to the main thread for rendering. Once new data arrives, the main thread should update the UI, e.g. switch from showing a loading circle to showing the actual image.
However, without user input, my main thread is sleeping, so it never runs any code that could react to the new data that arrived. To fix that, the loader thread sends a user event, which wakes the main thread up, so that it can run and handle the new data. My user event also contains information about what exactly happened with the loading, e.g. if an image couldn't be loaded, the main thread will be told this way.

**Comment by mickvangelderen** [comment]
You could already achieve this through [EventLoopProxy::wakeup](https://docs.rs/glutin/0.21.0/glutin/struct.EventsLoopProxy.html#method.wakeup) previously but I guess it is kind of nice to send a payload along with the signal.

**Comment by cheako** [comment]
How often is it that:
1. Winit must run on the main thread?  If this is a requirement, and I reasonably think it could be, this is news to me.  Another case where the documentation is woefully incomplete, the run() function needs to indicate in what cases it must run on the main thread.
1. The client(code that calls into winit) would need to also run on the main thread.  For any platform this would seem to be limited to a static number of things.  If practical it might be better for winit to just implement APIs for these few tasks as that would reduce repeated code.

**Comment by Osspial** [comment]
@cheako Neither of those points seem to be related to this issue, so I ask that you open new issue(s) to discuss them. If you don't have any more questions to ask about `send_event`, please close this issue.

**Comment by cheako** [comment]
I'm trying to understand why this feature is a thing and how bad do I need to keep it for my libraries that wrap winit.

Those two points are my guess as to when and why one thread would need to wakeup the winit event loop.

**Comment by aloucks** [comment]
> How often is it that:
> 
> Winit must run on the main thread? If this is a requirement, and I reasonably think it could be, this is news to me.

This requirement isn't unique to Winit. GLFW works the same way. It's due to the way that the underlying platform APIs work. Custom user events provide a way to send messages back to the main thread.

**Comment by ZeGentzy** [comment]
@cheako These two points do not seam related to the original issue. Please open a new ones, so that people searching similar issues can find them in the future.
