### ISSUE TITLE
`EventsCleared` not dispatched on iOS after `RedrawRequested`

### ISSUE THREAD

**Issue by aleksijuvani** [rust-windowing/winit#1087]
I'm calling `request_redraw` in `EventsCleared`, but no new `EventsCleared` events come in after I've finished drawing the frame, unless there is another event from the device, i.e. a touch event. So I have to keep tapping the screen in order to get my application to draw new frames. This is not consistent with what I'm seeing on macOS and Windows where new `EventsCleared` and `RedrawRequested` events keep coming in.

This is reproducible with the request_redraw example if [this line](https://github.com/rust-windowing/winit/blob/8a1c5277eb96d25d2c5e821eb24aa4a4e3020b74/examples/request_redraw.rs#L24) is commented out. As it appears, this happens only if the control flow is set to `ControlFlow::Poll` or `ControlFlow::Wait`, and it seems to be possible to work around this by setting the control flow to `ControlFlow::WaitUntil(std::time::Instant::now())`.

**Comment by mtak-** [comment]
Hopefully this isn't too rambly. I'm writing down my thoughts about this in case someone else (or me a week from now) finds it useful.

The iOS backend requests a redraw from the os via `setNeedsDisplay`. My suspicion is that `-[UIView setNeedsDisplay]` does not work outside of the UIEvent context. `CFRunLoopObserver`s are triggered without any active UIEvent. iOS uses observers to fire off meta-events like `EventsCleared`. Functions like [`stop:`](https://developer.apple.com/documentation/appkit/nsapplication/1428473-stop?language=objc) on macos have a delayed effect in the context of observers (waits for the next NSEvent). I think a similar thing is happening here.

> As it appears, this happens only if the control flow is set to ControlFlow::Poll or ControlFlow::Wait, and it seems to be possible to work around this by setting the control flow to ControlFlow::WaitUntil(std::time::Instant::now())

`WaitUntil(Instant::now())` always modifies the `CFRunLoopTimer`'s next fire date. Apple mentions that this is [relatively expensive](https://developer.apple.com/documentation/corefoundation/1542501-cfrunlooptimersetnextfiredate?language=objc), so that might be triggering something in UIKit which makes this work. `Poll`/`Wait` could probably do something similar.

It would not surprise me if there are more UIKit setters/side-effecting functions that do not work properly while handling `EventsCleared`, but I haven't investigated.

There are a couple of other interesting bits with `RedrawRequested` on iOS/macos as well.
- `-[UIView setNeedsDisplay]` has no effect for views _directly_ backed with gl/metal layers.
- Redrawing every time the eventloop clears events is likely to just block the main thread for long chunks of time when using metal ("waiting for next drawable"). I think this is mostly harmless and only manifests as a frame of input lag. It's up to users to use a display link to more intelligently fire off `redraw_requested`.
- iOS will request redraw events when backgrounded if the view is not _directly_ backed with a gl/metal layer. It does this in order to pretend like the app is already running when foregrounding it again. This works fine for native UIKit based apps; however, if the view's main layer has a gl sublayer (maybe metal too?), then drawing while backgrounded is actually a bug! I dunno how much this comes up in practice. But gfx does add a metal sublayer to `UIView` that don't already  have one, so it could actually be affecting users now.

There's lots of room to improve this part of the iOS backend.

**Comment by mtak-** [comment]
This is fixed by: https://github.com/rust-windowing/winit/pull/1133
