### ISSUE TITLE
I've got "Unexpected GetClientRect failure"

### ISSUE THREAD

**Issue by oligami** [rust-windowing/winit#1107]
# Unexpected GetClientRect failure
I 've got this panic on x86_64-pc-windows-msvc. I think this error has occurred just because `event_loop` dropped while `window` was alive. 
Writing this panic in the document may be good solution.

# Code
```
use winit::window::Window;
use winit::event_loop::EventLoop;

use std::thread;
use std::sync::mpsc;

fn main() {
    let (window_sender, window_receiver) = mpsc::channel();
    let handle = thread::spawn(move || {
        let event_loop = EventLoop::new();
        let window = Window::new(&event_loop).unwrap();

        window_sender.send(window).unwrap();
    });

    handle.join().unwrap();
    let window = window_receiver.recv().unwrap();
    let inner_window_size = window.inner_size(); // panic here!
    println!("{:?}", inner_window_size);
}
```

**Comment by sumit0190** [comment]
I faced something similar today (although it turned out that I was passing around `Window` objects needlessly) so I looked into it a little.

I don't think the `event_loop` being dropped has anything to do with it - `Window` doesn't even have a reference to it, right? At first I thought maybe `GetModuleHandleW` isn't the right way to get an `HMODULE`, but replacing it with `GetModuleHandleExA` yields the same result. A quick look at the error code shows that an invalid window handle is being passed to `GetClientRect`, so clearly something somewhere is being invalidated.

Also, the fact that you can get around it by calling `join` later (after getting the size, in this example) is fishy.

@Osspial I can take a further look at this with your guidance. :)

**Comment by Osspial** [comment]
@sumit0190 Thanks for offering! I believe you're right that the problem isn't that the `EventLoop` is being dropped, but the underlying cause is similar: the event loop thread is being destroyed. In win32, event loops are strongly tied to the thread they're initialized in, and windows are strongly tied to their parent event loop. Thus, when the event loop thread finishes, the event loop is destroyed alongside all windows that are associated with that event loop.

Strictly speaking, `EventLoop`s shouldn't be created off of the main thread since other platforms require that the event loop run on the main thread (macOS is the main desktop platform I'm aware of that requires this). Doing that is a cross-platform compatibility hazard, even though it *is* strictly possible on some platforms. However, that isn't documented anywhere within Winit, and it's probably something we should explicitly say.

**Comment by sumit0190** [comment]
@Osspial Aah, I see. My understanding on Win32 was incorrect then - I thought that creating an `EventLoop` object spawns another thread that runs forever until the parent terminates. Since a thread spawned inside another thread is considered to be the child of the main thread (and not the first thread), I thought that there would be no reason for the new thread to terminate before the main thread.

So the solution would be to keep the new thread alive until necessary, perhaps, by calling `join` only at the end?

**Comment by Osspial** [comment]
@sumit0190 I'd say to disallow it, but provide an escape hatch if people absolutely need to do it. I've created a PR implementing that on Windows here: #1186.
