### ISSUE TITLE
macOS: Closing window doesn't happen until the mouse cursor has moved

### ISSUE THREAD

**Issue by pftbest** [rust-windowing/winit#1117]
Version: 0.20.0-alpha3
OS: Mojave 10.14.6
Code: window example

Clicking on the red button in tile bar doesn't close the window until mouse cursor has moved.

Video: http://88.99.85.67:1337/bug264.mp4

**Comment by chrisduerr** [comment]
I've tested this myself and I cannot reproduce it with the latest master.

I'm also running 10.14.6 on a macbook pro.

**Comment by pftbest** [comment]
@chrisduerr Did you test with or without commit 7b707e7d758266fec28dd77ef8042be918e89f37?
It was added to master after I posted this issue.

**Comment by chrisduerr** [comment]
It was tested with it.

**Comment by pftbest** [comment]
I've just pulled latest master and I still have this issue.

@chrisduerr What model do you have? I've got 15'' 2015. Maybe yours is different and that's why it works fine for you?

PS I didn't make any modifications to my WM so it should be stock.

**Comment by chrisduerr** [comment]
I'm pretty sure I've got the 2018 model, the big one.

**Comment by kchibisov** [comment]
I'm also can't repro this one on default macOS 10.14.6 using the latest master. I've got `MacBook Pro (Retina, 13-inch, Early 2015)`.

**Comment by pftbest** [comment]
Ok, so how can I debug this? It's 100% reproducible on my side, so maybe you can suggest where to insert logs or other changes to figure out what is going wrong?

**Comment by syrel** [comment]
I am able to reproduce this.

Winit: https://github.com/rust-windowing/winit/commit/7b707e7d758266fec28dd77ef8042be918e89f37
OS: `OSX 10.15 Beta (19A501i)`
Mac: `MacBook Pro (15-inch, 2016)`
Example: `cargo run --example window_run_return`
Video: https://youtu.be/KS52dLAoWXQ

**Comment by parasyte** [comment]
This is also reproducible for me. When pressing the close button, the following log lines are emitted immediately, followed by the event loop callback receiving the `CloseRequested` event:

```
[2019-09-12T07:33:05Z TRACE winit::platform_impl::platform::window_delegate] Triggered `windowShouldClose:`
[2019-09-12T07:33:05Z TRACE winit::platform_impl::platform::window_delegate] Completed `windowShouldClose:`
```

Setting `ControlFlow::Exit` at this point doesn't exit the event loop until it receives another event like moving the cursor or pressing any key.

Using a key to exit the event loop only seems to work because the event loop just so happens to receive a `keyUp` or repeated `keyDown` event after `ControlFlow::Exit` is set.

**Comment by lordnoriyuki** [comment]
I can also reproduce reliably. macOS 10.14.6.

**Comment by bschwind** [comment]
Also able to reproduce. 

OS: `macOS 10.14.5`
Model: `MacBook Pro Retina 13", Mid-2014`
Winit Version: `0.20.0-alpha3` (checksum is `27c947714bd09779bb28fb7ac85685d5b68ab60d17349ed0ea7ae9484726024d`, sorry I don't know how to get the git sha1 by looking at `Cargo.lock`)

**Comment by vbogaevsky** [comment]
So far I see that `window_should_close()` in `window_delegate` returns for some reason `NO`. If I change it to  `YES` (and according to [this](https://developer.apple.com/documentation/appkit/nswindowdelegate/1419380-windowshouldclose?language=objc) it should return `YES` in order to close the window) the window closes, but the app runs until it receives new event.
