### ISSUE TITLE
Key Repeat events look like Key Pressed events.

### ISSUE THREAD

**Issue by cheako** [rust-windowing/winit#1184]
When A key is held down, on X11, multiple events for "state: Pressed" are emitted.

This is an example of the repeated event.
Sep 24 15:18:50.618 TRCE WindowEvent { window_id: WindowId(X(WindowId(50331649))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 45, state: Pressed, virtual_keycode: Some(X), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }

Is this designed behaviour?  It's causing me issues and I don't think it's the correct way to implement this.

**Comment by OvermindDL1** [comment]
Hmm, that does seem odd if so.  X itself sends a keyup then a keydown (always directly adjacent) in the event buffer (makes it easy to get a keyup and then `peek` if the next event is a keydown of the same key to know that it is an auto-repeat if you want to do some special functionality).

**Comment by Osspial** [comment]
I'm not going to say it's the *designed* behavior (it's more incidental to how the underlying platform APIs work), but we are aware of this behavior and it's what's expected right now. We intend to redesign the keyboard API at some point since it's got numerous issues and I believe this would be on the docket to fix then (see #812), but work on that hasn't been started and it likely won't get started until `0.20` exits alpha and gamepad support gets implemented.

**Comment by cheako** [comment]
duplicate of #753
