### ISSUE TITLE
COM initialization on Windows doesn't work in combination with cpal

### ISSUE THREAD

**Issue by RoyJacobs** [rust-windowing/winit#1185]
There is an issue with COM initialization on Windows in the current winit alpha release, in combination with the cpal audio crate.

A reproduction scenario is here: https://github.com/RoyJacobs/cpal-winit-repro

The root cause seems to be that winit is initializing COM with COINIT_APARTMENTTHREADED whereas cpal initializes COM with COINIT_MULTITHREADED.

I've also opened RustAudio/cpal#330 which fixes the issue by changing cpal's COM threading model from `COINIT_MULTITHREADED ` to `COINIT_APARTMENTTHREADED `. However, I'm not sure this is actually correct or simply a workaround of an issue on winit's side.

As my repro shows, cpal + winit 0.19 work fine together. So the question is: Is this an issue on winit 0.20's side or does this need to be addressed on cpal's side?

**Comment by Osspial** [comment]
I remember making this change, actually. We do this because we use the OLE APIs to manage file dropping, and OLE requires `COINIT_APARTMENTTHREADED` to work.

There's information on the differences between two modes [here](https://blogs.msdn.microsoft.com/larryosterman/2004/04/28/what-are-these-threading-models-and-why-do-i-care/). TL;DR `COINIT_MULTITHREADED` makes COM objects behave in a truly multithreaded manner, and `COINIT_APARTMENTTHREADED` ties their lifetime to the thread they were created in and dispatches update events to the object's thread for processing.

**Comment by RoyJacobs** [comment]
Right, but is this something that needs to be addressed in winit? Will the need to use apartment threading go away with the new event loop?

In the PR for cpal I've proposed that they use apartment threading as well, but may have issues on their side since this would require all threaded interactions to be carefully managed (as mentioned in the description on MSDN).

**Comment by RoyJacobs** [comment]
As suggested in the cpal issue, I am now creating my winit event loop in a separate thread and this solves the issue for now.

**Comment by Osspial** [comment]
I don't think this is something that *can* be addressed in Winit, unfortunately. Initializing COM with `COINIT_APARTMENTTHREADED` is the only way we can provide a reasonable file drag/drop implementation.

It's worth noting that Winit's event loop needs to be created on the main thread in order to work on all platforms - doing it elsewhere will panic on macOS and iOS, and I don't believe it will work on WASM and Android once we have those implementations on maser. Unfortunately, this hasn't been documented behavior, but I've opened a PR addressing that: #1186.

**Comment by RoyJacobs** [comment]
Would it be safe for me to this conditionally, though? I.e. on Windows spawn the event loop on a thread, on other platforms do it without the thread?

**Comment by Osspial** [comment]
@RoyJacobs Well, yes, but from what I've seen of CPAL's API it has to own its calling thread to work at all (see [`EventLoopTrait::run`](https://docs.rs/cpal/0.10.0/cpal/traits/trait.EventLoopTrait.html#tymethod.run)). Wouldn't it make more sense to put CPAL's processing in a separate thread instead?

**Comment by RoyJacobs** [comment]
Yes, possibly. There's some work underway there to remove the event loop altogether, so we'll wait and see. Good to know there are some workarounds available, regardless :) Thanks!
