### ISSUE TITLE
Resize cursor not showing on Wayland

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1236]
This has been reported to Alacritty in https://github.com/jwilm/alacritty/issues/2893.

It seems like resizing is still possible, however the correct cursor doesn't show up anymore on Wayland.

Might be related to the recent changes to the cursor that were don by @kchibisov iirc?

**Comment by kchibisov** [comment]
My cursor PR only added option to set an icon, otherwise - no extra handling, however we need to bisect it first, I guess. I can't repro this issue on sway 1.2 though, so probably something GNOME specific.

**Comment by kchibisov** [comment]
Ok, I've bisected and it's something related to my PR, I'm not sure what is going on here, since after a click on a border everything is fine. The one thing I've noticed is that GNOME relies on CSD and QT/Gtk showing a different icon for resize, so maybe its somehow related? Before we didn't have icon at all, so it was able to disappear over time on GNOME Wayland.
