### ISSUE TITLE
winit alpha seems to interact badly with gilrs. 

### ISSUE THREAD

**Issue by photex** [rust-windowing/winit#1250]
Howdy!

While I'm extremely happy to see winit working towards gamepad input support; I wish that this was leveraging gilrs instead of writing everything from scratch. Gilrs does all the things you need already. 
In either case, currently if I build an app using the winit beta4 and am using gilrs, there is a conflict between the implementations apparently. I'm still trying to figure out if that's entirely the case, but a large number of errors are logged from the force feedback module in gilrs if I use it with winit. I still get other gamepad events.
The error logged: `[2019-10-29T12:29:47Z ERROR gilrs_core::platform::platform::ff] Failed to modify effect of gamepad File { fd: 11, path: "/dev/input/event13", read: false, write: true }, error: EINVAL: Invalid argument`

Perhaps gamepad support could be feature gated? I'd be willing to contribute a PR. But again, I wasn't around for any discussion that might have listed reasons not to use gilrs, but I'd love it if winit could reconsider that approach.

**Comment by photex** [comment]
Whoops, one detail I forgot. This error only pops up when you call Gilrs::next_event from inside the winit event_loop. And since it appears that going forward you'll only be able to use winit using its event loop (rather than the previous poll_events interface), I can't see a way around this aside from using another thread... which seems overkill.

**Comment by photex** [comment]
Sorry, I wrote `beta4` everywhere; I meant *alpha4*.

**Comment by Osspial** [comment]
Hi, and thanks for opening this issue.

I can't speak directly to the issue you're having, since it seems to be a Linux issue (cc @murarth). However, I can answer your questions about why we aren't using gilrs. The primary technical benefit for moving gamepad support into Winit is that the OS can dispatch gamepad events directly into Winit's event loop. That comes with a couple concrete improvements:
- On some platforms (Windows, macOS), gilrs needs to spawn a secondary event loop on a background thread in order to receive gamepad events. Handling gamepad events directly within Winit lets us get rid of that secondary thread.
- Gilrs has a polling-based API, where the program needs to ask the OS for the gamepads' current state. This is relatively fine for games, which necessarily update at least 60 times per second, but it doesn't work for desktop applications, which generally want to go idle when not processing events in order to save CPU time and power. Having Winit own the gamepad implementation allows it to implement a notification-based API, where the OS delivers gamepad events into Winit's event loop and applications handle the events on demand.

I'd be absolutely fine with integrating some of Gilrs's work into Winit where appropriate, but the code needs to live within Winit proper.

----

Also, why do you suggest feature gating the gamepad API? I can get doing that if we were to use Gilrs as a base, but if the implementation lives within Winit there shouldn't be any problem to having it always be enabled.

**Comment by photex** [comment]
Thanks for the context and explaining it all. For what it's worth, I think having both polling and callback/event-loop oriented apis is worth having. As you've said, some applications are better served by an event loop, while others are better off polling.

My suggestion to feature-gate it was based on reasons for wanting to continue using gilrs until winit has a comparable feature set for game related input which may be some time off in the future, especially if the in-progress gamepad support interacts badly with the current best option for gamepad input for a rust application or game. SDL2 for example can selectively enable subsystems at runtime, so that would also be a possible solution.
