### ISSUE TITLE
Toggling fullscreen on Mac errors if Command key is held

### ISSUE THREAD

**Issue by swiftcoder** [rust-windowing/winit#1269]
If you take a minimal sample for toggling borderless fullscreen via keyboard shortcut, and you require the shortcut to include the Command key, Mac OS will print errors to the console when exiting fullscreen, accompanied by the system alert sound.

```
2019-11-09 18:28:30.309 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
2019-11-09 18:28:31.991 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
2019-11-09 18:28:33.518 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
2019-11-09 18:28:35.101 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
2019-11-09 18:28:37.041 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
```

Here's a minimal sample for winit-0.20.0-alpha4 that repros the issue:
https://gist.github.com/swiftcoder/740b138e00b49ee425222fe87a2efa0c

This error will also make the window **invisible** if you are rendering to it (not shown in the interests of keeping the repro case restricted to just winit).

Note that the issue does not reproduce if you use a different modifier key (i.e. `ctrl`).

**Comment by hatoo** [comment]
> Some(event::VirtualKeyCode::F) if modifiers.logo => {

This code matches both `Pressed` and `Released` event.
In my observation, it seems that Key events during toggling fullscreen are ignored but not ignored if `Command` key is held. I don't know why.

Also `window.set_fullscreen` not affects immediately when returned. It takes some time to effect. And it involves error when called during the time.

So the error happens because of inputting Cmd-F send both `Pressed` and `Released`  events and involves calling `set_fullscreen` twice in a short period time.

**Comment by goddessfreya** [comment]
I'm unassigning @vbogaevsky since this issue appears to have had no traffic for over a month.

@hatoo Could you look into a solution to this problem?
