### ISSUE TITLE
Use events without windowing

### ISSUE THREAD

**Issue by kvark** [rust-windowing/winit#1278]
We are discussing the API model that WebGPU would expose for native applications that aim to target for the web. Since JS is based on events, exposing the native API in terms of events and an event loop would mean minimum amount of glue between the app and the browser.

I wonder if it would be possible (or makes sense at all) to integrate our events into `winit` events somehow?

Another side questions is - for the applications that don't need any windowing, it would be unfortunate to depend on the *whole* winit. If we plan on integrating with `winit`'s events, would you consider moving it outside of `winit` into a separate crate?

**Comment by Osspial** [comment]
This is a tricky question to answer without specifics. Could you elaborate? It's difficult for me to imagine what useful APIs you could pull out from Winit that are independent from the windowing API, since most of the current event loop is structured around handling and dispatching window events, but that could absolutely be for lack of imagination.

**Comment by kvark** [comment]
Windows events are supposed to be contained within `Event::WindowEvent` variant. That leaves out device events, user stuff, and some other things.

We have an async API, so the events it would need to handle are:
  - different kinds of errors that happened on the "gpu server" side
  - callbacks from mapping and fences

Now that I think of it more, we'd be better off wrapping that async API in futures, used with whatever event loop that can drive the futures. On that note, I think we can close this.
