### ISSUE TITLE
Web backend sends RedrawRequested too often

### ISSUE THREAD

**Issue by ryanisaacg** [rust-windowing/winit#1305]
An expected user pattern with the new API is to request redraw after every `EventsCleared`.

On web, the event handlers are run instantly as events come in, which means there can be many more `EventsCleared` than the user expects.

I can think of two ways to address this:
- Don't run the event handlers as often, and buffer up events with a minimum time between processing them. This adds latency where it isn't necessarily needed, so it may not be ideal.
- Only run `RedrawRequested` events on a timer determined by the browser `requestAnimationFrame` API, which does slightly break the API contract.

I'm not sure which of these mitigations is better, so I would welcome discussion.

**Comment by Osspial** [comment]
Why is this a problem? This behavior is also exhibited on Windows since there's pretty much no overhead between the platform event dispatcher and the Winit event closure, but I haven't found it to be an issue because real applications take long enough to process events (due to vsync, rendering, world updates, etc.) that events naturally get buffered up. Even if downstream users have unusually lightweight applications that can reach extreme framerates, that shouldn't pose any functional issues in their applications.

**Comment by ryanisaacg** [comment]
My understanding from a few user reports is that the redraws 'build up' over time, consistently producing more work than is handled.

**Comment by goddessfreya** [comment]
Won't redraw buildup be resolved by `redraw-requested-v2`?

**Comment by ryanisaacg** [comment]
It might be; once it lands on master, we can see if that fixes the problem.

**Comment by Osspial** [comment]
Do web platforms automatically aggregate duplicate `RedrawRequested` events into a single event?

**Comment by ryanisaacg** [comment]
Yes, if you request redraw multiple times before another `RedrawRequested` it should only produce one event

**Comment by tangmi** [comment]
@ryanisaacg I agree that `RedrawRequested` should only fire when `requestAnimationFrame` runs, but not necessarily every frame (so that non-game applications that don't change often can save battery life/cpu cycles). What do you think of a flag that producers of `RedrawRequested` can set/check to kick off a single `requestAnimationFrame` that is cleared when the `requestAnimationFrame` callback finishes? This would effectively debounce `RedrawRequested` events and let the browser  service the "request" when it best thinks it should. A downside of this is that the visuals could always be a frame behind (but I think that might always be the case if visuals are always handled in `requestAnimationFrame`'s callback...?)

**Comment by OvermindDL1** [comment]
> (but I think that might always be the case if visuals are always handled in requestAnimationFrame's callback...?)

From my understanding, `requestAnimationFrame` callback is called immediately before the browser renders a new frame, so there shouldn't be any delay?

**Comment by tangmi** [comment]
@ryanisaacg what do you think of using requestAnimationFrame as a timer of sorts for aggregating events into individual "frames"? Like, when any event happens, call requestAnimationFrame (and set a flag). Continue processing events and when the callback fires, trigger the MainEventsCleared event and then RedrawRequested (if the app has called Window::request_redraw) and clear the flag.

This way, MainEventsCleared/RedrawRequested only fires once per frame, but if no events are coming in it is not fired (nor is requestAnimationFrame called).

**Comment by OvermindDL1** [comment]
Something I do recall having an issue with with `requestAnimationFrame` is that if updating of the DOM or drawing anything or so happens outside of it's callback, the browser is free to interleave things, so you can get tearing and so forth.

**Comment by tangmi** [comment]
@OvermindDL1 I don't think that should be an issue for winit, but do you have docs describing that behavior? I thought that dom updates were always atomic (I guess, perks of being on the web vs e.g. wincomp) and that one of the reasons `requestAnimationFrame` exists is to force vsync.

**Comment by ryanisaacg** [comment]
I think we haven't seen new reports of this problem, and the events are being de-duplicated correctly. Aligning to `requestAnimationFrame` still might be a good idea, at least as a platform-specific setting.

**Comment by OvermindDL1** [comment]
@tangmi DOM updates themselves are atomic, however the rendered state of them is not, that happens asyncronously to the DOM updates in the common browsers.

https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Performance_best_practices_for_Firefox_fe_engineers

> Note that requestAnimationFrame() lets you queue up JavaScript to run right before the style flush occurs. This allows you to put all of your DOM writes (most importantly, anything that could change the size or position of things in the DOM) just before the style and layout steps of the pipeline, combining all the style and layout calculations into a single batch so it all happens once, in a single frame tick, instead of across multiple frames.

https://developer.mozilla.org/en-US/docs/Games/Anatomy

As well as from my understanding the draw calls won't happen until `requestAnimationFrame` returns as well.

**Comment by alvinhochun** [comment]
I think it makes sense to delay MainEventsCleared and RedrawRequested until the browser's event queue has been cleared. Any longer delay doesn't seem like a good idea.

There is a new-ish API [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask) (can be polyfilled using `Promise.resolve()`) which will queue a "microtask" to be executed after other tasks (see [this page](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#Tasks_vs_microtasks)). It might be possible for `winit` to use a microtask to detect that all queued DOM events are drained in order to limit the frequency of `RedrawRequested` without introducing a significant delay. `winit` can then queue the events like how its already doing for `ControlFlow::Poll` and drain the queue from the microtask.

I do have a bit of doubt whether it is really a good idea to trigger rendering (which may be a heavy process) inside a microtask, but the resulting effect shouldn't be any different than running from within a DOM event, except if the process modifies the DOM.

(Note to self: If I use `ResizeObserver` I need to keep in mind that those listeners might also run inside a microtask, so I need some hacks to make sure we also queue the resize events together.)

**Comment by Liamolucko** [comment]
> There is a new-ish API [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask) (can be polyfilled using `Promise.resolve()`) which will queue a "microtask" to be executed after other tasks (see [this page](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#Tasks_vs_microtasks)).

That's a bit backwards - microtasks get queued _before_ other tasks, so they aren't a solution to this issue.

That could probably be accomplished with `requestIdleCallback`, but [I'm not sure if that can be relied upon](https://w3c.github.io/requestidlecallback/#start-an-idle-period-algorithm), and it's not in Safari yet anyway.

**Comment by daxpedda** [comment]
I don't think this is actually an issue to begin with.
But Winit is definitely lacking a proper VSync event, see #2412 for that though.

I do think that the current use of `requestAnimationFrame` is wrong though and we should use `requestIdleCallback` or `setTimeout` (which is the recommended polyfill for `requestIdleCallback`) instead.

The big "improvement" we should do in the future though is use `requestIdleCallback` to "finish" the our event loop. Right now every single event, e.g. `Poll` or any Web API event callback, will start the whole Winit event loop from scratch and finishes it as well, that's why we are getting all these `RedrawRequested` events. The new event loop should look something like this:
1. An event or `Poll` starts the Winit event loop with `NewEvents`.
2. We schedule to end the Winit event loop with `requestIdleCallback`.
3. We handle any incoming Web API event through their callbacks.
4. `requestIdleCallback` kicks in and we end the Winit event loop with `MainEventsCleared`.

This would also be much closer to how other backends work.

The fact that browsers can throttle though is weird, but I'm not sure if this is an issue for us.

**Comment by daxpedda** [comment]
So I played around with this idea here: https://github.com/daxpedda/winit/commit/006cc8c50f83a33f6a405636836e440c1623ed1e.

It doesn't seem to be worth it, the idle callback happens so fast it almost never actually becomes useful and the event loop is closed right away without any new events coming in anyway.

This might be more useful under really high contention, so I'm happy to merge this into Winit if somebody actually manages to make this useful.

So right now, `RedrawRequested` will not be emitted unless you do `Window::request_redraw()`, except when the window is resized. I think everything else should be handled by #2412.

With that said, this can be closed.
Please feel free to reopen or comment on this issue if I missed or misunderstood something.
