### ISSUE TITLE
Gnome Wayland decorations behind system bar

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1312]
It seems like somewhere between the version glutin master currently uses (0.20.0-alpha4) and the latest master, the window decorations on Wayland with gnome have been broken.

Previously when starting a maximized window, the window bar would be visible, as it should be. However with the latest master, the window is 'offset', so the top of the screen is the top of the inner window (no decorations) and the decorations are behind the system bar.

This might be better explained with the screenshots from the original Alacritty issue: https://github.com/jwilm/alacritty/issues/3070

**Comment by Will-W** [comment]
I was the original reporter on alacritty and I'm happy to continue to help diagnose and try things.

**Comment by goddessfreya** [comment]
@Will-W  Can we get a git bisect for which commit breaks stuff?

**Comment by real-or-random** [comment]
I have the same issue, and for me it really depends on the shape of the gnome bar. If I use a theme where the gnome bar is rectangular with no margin around it (i.e., it starts at 0,0 and fills an entire rectangle like an ordinary window, then alacritty's position is correct). If I use a theme where the gnome bar has round edges and is positioned in the middle with margin around it, then alacritty's position is behind it.

**Comment by real-or-random** [comment]
Sorry, ignore my comment. I was under a wrong impression. This happens independently of the theme.

**Comment by Will-W** [comment]
Sorry for the delay - I've been away. I've run a bisect and the offending commit is 72fc6a74ec3da62355bacf860950e03b42dbd11b "on Wayland, drop resize events equal to the current window size".

Makes sense how that might have broken it.

**Comment by goddessfreya** [comment]
cc @kchibisov.

**Comment by kchibisov** [comment]
I'll take a look on it during the week. You'll never know how GNOME WAYLAND surprises you next time...

**Comment by vberger** [comment]
Looking at this commit, I suspect the issue is that `frame.resize(..)` should be called in all cases, and not only when `newsize != *size`, as SCTK internally redesigns the window geometry and I would not be surprised if Gnome relied on this to check that the window correctly responded to the maximization request.

I don't have a Gnome session to test it though.

**Comment by almindor** [comment]
I was hoping I could maybe test this but the fullscreen example (not even sure if that's the correct thing tho) does not work for me at all with wayland. Bordeless gives me a running app but nothing visible at all.

**Comment by Will-W** [comment]
My original tests, and the bisect I ran used http://github.com/chrisduerr/glutin . That's a fork of rust-windowing/glutin that tracks more recent winit. I was using the `window` example adding a `.with_maximized(true)` to the builder. @almindor it's `maximized` not fullscreen that's relevant here.

I have just tried a similar thing with winit directly, but none of the examples I tried (modified or unmodified) produced any visible output. Something appears in the alt-tab menu, but no window that I could see. I don't know what the expected behaviour is (this is still Wayland/Gnome/Fedora, tested on both 29 and 30).

**Comment by almindor** [comment]
@Will-W thanks I'll test with that. NOTE: winit examples alone won't produce anything on wayland (this is apparently a known issue) you need to run something that draws to the window to get any output in wayland.

**Comment by almindor** [comment]
This is what I get when using the "window" glutin example modified to maximize. You can see that there's a bottom offset so different behavior but still wrong. NOTE: fullscreen examples are broken for me, I get a 1/4th-ish sized window on them instead, but since that's probablty a different issue I'll open a new one for that.

![glutin_maximized](https://user-images.githubusercontent.com/1950958/70825402-8b2ace80-1da1-11ea-8bb1-2b63a2fd8945.png)

**Comment by Will-W** [comment]
From that screenshot, that looks like the same (incorrect) behaviour that I originally reported ([screenshot](https://user-images.githubusercontent.com/997500/70255225-535ad000-177e-11ea-8c50-78ac3d059f86.png)). And thanks for the info about Wayland, that makes sense.

**Comment by kchibisov** [comment]
Just to confirm what I see according to my testing with Fedora 31 and 3.34.x. The issue is only about **with_maximized(true)**, right? Since I can't trigger it after just by maximize/fullscreen, etc on window. It shows up only with `with_maximized(true)` (`startup_mode: Maximized` in alacritty).

**Comment by Will-W** [comment]
Yes, any later resize behaviour seems to work correctly. It's just the
attempt to start maximized that has an issue (in my testing).

**Comment by vberger** [comment]
It'd help to have a wayland trace of what happens, this can be done by setting the env variable `WAYLAND_DEBUG=1`, and the trace will be dumped to stderr.

**Comment by Will-W** [comment]
Here's the debug trace:
[maximized.txt](https://github.com/rust-windowing/winit/files/3978546/maximized.txt)

And the same test but without `with_maximized(true)`, in case that's of any use for comparison:
[non_maximized.txt](https://github.com/rust-windowing/winit/files/3978547/non_maximized.txt)
