### ISSUE TITLE
Support for Unix systems without Wayland

### ISSUE THREAD

**Issue by psumbera** [rust-windowing/winit#1325]
I'm looking into getting support for Solaris where there is no Wayland.

This seems to be needed to continue to deliver Mozilla Firefox and Thunderbird for Solaris.

I hope X11 support is enough. Though src/platform/unix.rs seems to expect to have both X11 and Wayland.

**Comment by vberger** [comment]
The winit logic is to try loading wayland, and fallback to X11 if it is not available. The wayland libraries are loaded using dlopen, so it should gracefully handle a system without wayland.

Or is there some issue with compilation on Solaris ?

**Comment by psumbera** [comment]
Thanks. I think I just need to add some 'target_os = "solaris"' to build it. But before that I need to do the same for: https://github.com/nix-rust/nix

**Comment by Osspial** [comment]
Out of curiosity, how does Firefox depend on Winit?

**Comment by dzduniak** [comment]
Sometimes you program on systems that are not running any display server and you may use some other means to provide user interface....

Sure you may check if display server is running before touching winit, but I think library should handle cases like that gracefully either way.

My recommendation would be to change `EventLoop::new()` (since it is usually where you start) to return `Result<EventLoop<>, EventLoopCreationError>` instead of panicking, so you could check the result and try to use your own "event loop" without explicitly catching panics.

**Comment by kchibisov** [comment]
you can build winit without wayland, since it's an optional feature (as well as x11).
