### ISSUE TITLE
Version 0.19.5 failed compiling on windows

### ISSUE THREAD

**Issue by lazytiger** [rust-windowing/winit#1327]
Hi, I found this compiling problem as follows:

Rust Version: 1.40
Platform: Windows 10

```
with `winit = "=0.19.5` got the following error
`error[E0308]: mismatched types
   --> C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.19.5\src\window.rs:440:9
    |
439 |     fn raw_window_handle(&self) -> raw_window_handle::RawWindowHandle {
    |                                    ---------------------------------- expected `raw_window_handle::RawWindowHandle` because of return type
440 |         self.window
    |         ^^^^^^^^^^^ expected enum `raw_window_handle::RawWindowHandle`, found struct `platform::platform::window::Window`
    |
    = note: expected type `raw_window_handle::RawWindowHandle`
               found type `platform::platform::window::Window`
`
```

when 0.19.4 and below seems ok

Is there something wrong with my environment or it's a bug?

**Comment by Osspial** [comment]
I have no idea how this error is even possible. I checked my version of `winit-0.19.5` downloaded from crates.io, and the source code your error reports is... wrong. This is the function your error reports as broken, taken straight from crates.io:

```rust
fn raw_window_handle(&self) -> raw_window_handle::RawWindowHandle {
    self.window.raw_window_handle()
}
```

I'm actually at a loss for words about this. I'd suggest deleting your cached crates and letting Cargo redownload them, because *something* bad clearly happened.

**Comment by lazytiger** [comment]
@Osspial You are right, this is totally weird. I removed cache and src, and rebuilt, all went right now. Thanks anyway.
