### ISSUE TITLE
Feature - Tab support

### ISSUE THREAD

**Issue by chichid** [rust-windowing/winit#1397]
I'm wondering if it would make sense to add tab support to this project's scope. I think tabs at least Win32 and OSX are tightly coupled to the concept of windows, and it would be a great addition as first class citizen of Winit. 

If interested, I can definitely fork and experiment with the idea. I know at least on Cocoa tabs are straight forward to implement.

**Comment by kchibisov** [comment]
Could you point to docs about win32 tabs, pls? I guess only macOS make it easy to support. On X11/Wayland you should implement them manually, since it's the same window actually. So at this point this API seems like out-of-scope and knowing that macOS tabs require an option to create window, clients can easy implement them out side of winit without too much effort. But if the goal is roll tabs on all platform in a unique way, it's not possible on at least X11/Wayland so you should handle them and draw them in your app anyway.

**Comment by chichid** [comment]
@kchibisov you're right, I'm chocked on how hard it is to implement tabs outside of MacOS.... I guess this is out of scope since it's the content of the window.
