### ISSUE TITLE
Support for requestAnimationFrame

### ISSUE THREAD

**Issue by ryanisaacg** [rust-windowing/winit#1493]
It's best to do all rendering on the web in requestAnimationFrame, but currently Winit does not respect this. Partly this is due to the API contract: `request_redraw` can't wait for the runtime to come back with a callback, because it must occur after the next `MainEventsCleared`.

A web-specific extension that produces `RedrawRequested` events is probably the way forward here, but I would be open to other ideas.

**Comment by kchibisov** [comment]
Does this event is basically tells you when to draw, like artificial vsync, etc?

**Comment by ryanisaacg** [comment]
Basically, see the [relevant MDN.](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)

> You should call this method whenever you're ready to update your animation onscreen. This will request that your animation function be called before the browser performs the next repaint. The number of callbacks is usually 60 times per second, but will generally match the display refresh rate in most web browsers as per W3C recommendation. requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden <iframe>s in order to improve performance and battery life.

**Comment by kchibisov** [comment]
I'm just trying to understand how it maps to `wl_surface::frame` https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface . It seems like they are similar.

**Comment by ryanisaacg** [comment]
I'm not familiar with Wayland, but I would say they serve just about the same function.

**Comment by kchibisov** [comment]
You're basically requesting when to draw by doing `wl_surface::frame` and draw in a callback you've provided to this function. So, your pipeline is to draw once, call this function in the end, then just draw in a callback + execute this function each time you finished your drawing.

There' were some ideas on how to implement this Wayland thing more generically [here](https://github.com/rust-windowing/glutin/issues/1231#issuecomment-546086364).

**Comment by chemicstry** [comment]
What about replacing the zero `Timeout` in `ControlFlow::Poll` with `requestAnimationFrame`? AFAIK this does not break the API as poll interval is undefined and could be one frame. Also the current poll implementation with zero timeout is useless because it causes 100% cpu load. I have a PoC here https://github.com/chemicstry/winit/commit/3d5274b9ccf0a6212cda3b01d058000f2555bfec

**Comment by ryanisaacg** [comment]
@chemicstry I haven't found that the current implementation causes 100% CPU load, but the web is finicky so I can definitely see that problem cropping up on some systems.

This solution does look good to me as a stopgap, but doesn't fully address the problem. Ideally it should be possible to use both `ControlFlow::Wait` and `requestAnimationFrame`. I would still merge a PR along these lines though!

**Comment by chemicstry** [comment]
It probably depends on how fast the browser calls zero timeout again. Some insert artificial delay to prevent bad javascript from freezing the page.

Anyways, great, I will create a PR. Just need to write stdweb implementation and cleanup the code.

**Comment by grovesNL** [comment]
We might also want to consider some options around `requestPostAnimationFrame` for WebGL and WebGPU: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#Use_requestPostAnimationFrame_not_requestAnimationFrame

**Comment by chemicstry** [comment]
From what I understood about `requestPostAnimationFrame`, it is mainly intended for DOM reads, because all changes are flushed just before the call. In other words, when you change DOM and then try accessing it before redraw, it causes a forced synchronous redraw. So by having all DOM reads in `requestPostAnimationFrame` you are guaranteed not to force a synchronous redraw.

I don't see any use of it for winit which purely deals with canvas and doesn't do any DOM reads. I would like to be corrected if I misunderstood something.

**Comment by grovesNL** [comment]
I don't have much knowledge about `requestPostAnimationFrame` because it's still a relatively new feature (I still use `requestAnimationFrame` only at the moment). I just noticed it mentioned in that WebGL Best Practices article and thought it seemed relevant here. The article mentions that `requestPostAnimationFrame` allows for the most frame time (possibly avoiding missing vsync) based on task/microtask priority in general though – not necessarily DOM reads.

**Comment by chemicstry** [comment]
Well, the html spec is a bit loose on this, but it seems that most browsers call `requestAnimationFrame` callback instantly after vsync, meaning that that whole frame time is available for rendering next frame. Here's one of the tools that show time difference between vsync and callback https://www.vsynctester.com/

**Comment by Osspial** [comment]
Closing since #1519 was merged.
