### ISSUE TITLE
ModifiersChanged message does not indicate keyboard device_id

### ISSUE THREAD

**Issue by maaku** [rust-windowing/winit#1514]
The `modifiers` field in `winit::event::KeyboardInput` is marked as depreciated, and a note in the documentation says that applications should instead handle the `ModifiersChanged` message (and presumably track the resulting value themselves). However the `KeyboardInput` event has a `device_id` field while the `ModifiersChanged` message does not. Strictly speaking, this is therefore a decrease in functionality.

To illustrate, consider a system that has two keyboards attached--which is not so crazy as it sounds when you consider bluetooth keyboards, or special purpose devices. If a modifier key is pressed on one device, conceivably that could be isolated from the other in the prior model. However with the `ModifiersChanged` message pressing any modifier key on any device affects the key input of all other devices.

Although this is certainly and edge case, it appears to me to be a bug. Perhaps the `ModifiersChanged` event type should be augmented to include a `device_id`?

**Comment by Osspial** [comment]
`device_id` in `WindowEvent` has only ever been implemented on Linux, and from what I can tell it's pretty much impossible to expose on all the other OSes. All the non-Linux backends just pass in a dummy value for that field. As it stands, if you need to distinguish between devices when handling input you should listen for `DeviceEvent`s instead of `WindowEvent`.

In light of that we've been moving towards removing `DeviceId` from `WindowEvent` completely (see #1374), but that PR needs more design work before it can move forward.
