### ISSUE TITLE
[macos] Resized event sizes not matching resulting inner-size

### ISSUE THREAD

**Issue by alexheretic** [rust-windowing/winit#1516]
I have a report for Robo Instructus for a mismatch between `Resized` event sizes and the actual window `.inner_size()` during a fullscreen startup. This is crucially relied upon currently as the framebuffer is not resized until these sizes agree with each other after a resize, so this results in a blank screen.

>  This is on a Mac Pro (late 2013) running Mac OS X Mojave, with 32 GB of RAM and two AMD FirePro D300 2 GB GPUs 

From logging I can see the latest `Resized` physical size is `(1920, 1178)` while the window's reported inner-size is `(1920, 1200)`. 

On the face of it, since I expect this to be fullscreen the latter size 1920x1200 seems correct. So is this a bug in the resized events?

**Comment by alexheretic** [comment]
I also noticed windows resize events will go out of sync with inner-size when switching between fullscreen & windowed sometimes. 

I'm going to "solve" this now by not using `Resized` events. Instead using the `inner_size()` as the source of truth.

```rust
let mut earlier_size = window_ctx.window().inner_size();

events.run(move |event, _, control_flow| {
    match event {
        Event::MainEventsCleared => {
            let window_size = window_ctx.window().inner_size();
            if earlier_size != window_size {
                window_ctx.resize(window_size);
                // resize other stuff
            }
        }
    }
});
```

This seems to work ok. 

But if the `Resized` events cannot be guaranteed to reflect the actual inner-size it makes sense to remove them. At least I don't understand how they can be used reliably without this property.

**Comment by kchibisov** [comment]
>But if the Resized events cannot be guaranteed to reflect the actual inner-size it makes sense to remove them. At least I don't understand how they can be used reliably without this property.

Or fix them, since, it's a bug, and they should be the same.

**Comment by mitchmindtree** [comment]
I have my hands on a mac for a moment so thought I'd test this, but I'm unable to recreate this issue locally.

macOS Mojave 10.14.6 MacBook Pro (15-inch, 2016)

To test this, I modified the `fullscreen.rs` example to print out `Resized` events along with the result of `inner_size` immediately afterwards. When opening the window in both borderless and exclusive modes, the two values always seemed to match perfectly in my test cases. I did notice that two resized events were emitted in borderless mode: the first with a size 3360x2010 and another with a size of 3360x2100 (the fullscreen dimensions) immediately after, but this seems acceptable.

I also tried testing the `window.rs` example to only print out `Resized` events and the result of `inner_size` immediately afterwards. The two values almost always match. **However**, very occasionally the `inner_size` value differs slightly while the resize is in progress. I consider this to be expected behaviour however, as the window size can change between the moment the `Resized` event was emitted and the call to `window.inner_size()` occurs. In the case of fullscreen-ing the window, the result always seems to match afterwards, in my case a physical size of 3360x2100 is reported both from the `Resized` event and the call to `window.inner_size()`.

Could you perhaps provide a minimal example that demonstrates the behaviour you're seeing? A modification of one of winit's examples might be easiest.

> I'm going to "solve" this now by not using Resized events. Instead using the inner_size() as the source of truth.

In general I would opt for the opposite of this approach (that is, preferring to rely on `Resized` instead of `inner_size()`) due to the potential inconsistencies that can be caused by a resize-in-progress as mentioned above. But I can understand why you've taken the approach that you have for a temporary workaround if you're seeing incorrect values from the `Resized` events.

**Comment by alexheretic** [comment]
I can't reproduce this myself. It was a bug report but I could see it happening from the error logs, I only logged after the two sizes were stable for a few seconds and different from each other. 

The reporter could only reproduce on the mac pro, not on his macbook (https://steamcommunity.com/app/1032170/discussions/0/2153224488980878439/). 

When they disagreed, the inner-size matched the actual number of pixels of the screen. Hence why I prefer inner-size now. 

Honestly I didn't imagine that they could even be technically distinct concepts, so it was quite surprising that they _can_ be different. I'm happy that at least there is a solid workaround.
