### ISSUE TITLE
[needs-upgrade] mio 0.7

### ISSUE THREAD

**Issue by kaimast** [rust-windowing/winit#1520]
Not sure if there is a specific issue blocking this but it would be great to see winit (and associated packages) to be updated to mio 0.7.

I can create pull request if that would help.

**Comment by murarth** [comment]
winit depends on mio-extras, which doesn't yet support mio 0.7. mio-extras has an open issue about this: dimbleby/mio-extras#7

Otherwise, winit also has a dependency on mio through smithay-client-toolkit, but there's already an updated version of that package that supports mio 0.7, so we shouldn't have a problem there.

**Comment by kaimast** [comment]
> Otherwise, winit also has a dependency on mio through smithay-client-toolkit, but there's already an updated version of that package that supports mio 0.7, so we shouldn't have a problem there.

I just took a look at this. It seems like the update from SCTK 0.7 to 0.8 might be a little painful as the API changed a lot. 

Also mio 0.7 removed level-triggered events, which winit uses at least in some places.

**Comment by kchibisov** [comment]
SCTK 0.8 will bring calloop back for Wayland in winit. Though, it'll take some time to update to it.

**Comment by kchibisov** [comment]
>Also mio 0.7 removed level-triggered events, which winit uses at least in some places.

It's nearly impossible to use `edge-triggering` in windowing library, it already caused problems for sctk, when events are missing, etc, so I'm not sure that winit should be updated to it. From what I see it's impossible to use mio with edge-triggering for anything other than networking.

**Comment by chrisduerr** [comment]
> It's nearly impossible to use edge-triggering in windowing library, it already caused problems for sctk, when events are missing, etc, so I'm not sure that winit should be updated to it. From what I see it's impossible to use mio with edge-triggering for anything other than networking.

From what I see, this just means that the code previously in `mio` would now need to be implemented upstream? For oneshot this is fairly simple, by just deregistring after receiving an event. But for level it's more complicated.

**Comment by kchibisov** [comment]
I start feeling that using calloop could be not actually a bad idea over mio, so it'll be at least interesting to investigate into that option. It does have level/oneshot/edge triggering, and has support for epoll/kqueue and will be used on Wayland backend anyway by default.

**Comment by kaimast** [comment]
> I start feeling that using calloop could be not actually a bad idea over mio, so it'll be at least interesting to investigate into that option. It does have level/oneshot/edge triggering, and has support for epoll/kqueue and will be used on Wayland backend anyway by default.

`calloop` might be the best way to go if it is already a dependency. You are probably already aware but `cargo audit` started complaining about the dependency on `mio` 0.6.

```Crate:  net2
Title:  `net2` crate has been deprecated; use `socket2` instead
Date:   2020-05-01
URL:    https://rustsec.org/advisories/RUSTSEC-2020-0016
Dependency tree:
net2 0.2.34
├── miow 0.2.1
│   └── mio 0.6.22
│       ├── winit 0.22.2
```

I would still be willing to help with this if needed, albeit I have not a massive knowledge of the `winit` codebase.

**Comment by murarth** [comment]
The X11 backend was using `calloop` until the DPI overhaul implementation, which added the requirement to directly call the user-provided callback when handling a `ScaleFactorChanged` event. This is in conflict with the `calloop` model, which seems to be fundamentally based around collecting events from sources, then later delivering those events to the application. Therefore, I don't think using `calloop` for the X11 backend is a viable option unless `calloop` changes in this regard.

However, I think it is possible for the X11 backend to migrate to `mio` 0.7. Currently, we're only using channels from `mio_extras` and I think this can be straightforwardly replaced with a combination of `std` mpsc channels and a `mio::Waker` instance. And since it appears that SCTK no longer depends on `mio` at all (`calloop` now depends on `nix` instead of `mio`), that would complete winit's migration to `mio` 0.7.

I'm not aware of issues relating to edge-triggering. If someone could link me to an issue on this subject, that would be great. All I can say for now is that xlib does appear to read its connection until `EAGAIN` is returned and winit already completely drains the `XConnection` instance of events on each event loop iteration. So, I think we should be able to manage any issues resulting from edge-triggered poll events.

**Comment by kchibisov** [comment]
FYI Wayland backend is using calloop without any issues even with ScaleFactorChanged event. Also, callop API was changed.

**Comment by murarth** [comment]
> callop API was changed.

Oh, I was not aware. I'll take another look at `calloop` and see if it's now suitable for the X11 backend.

**Comment by murarth** [comment]
I misstated the problem with `calloop`'s API in my previous comment. The issue is that `calloop` requires a callback to consume source events at the time the source is registered (see [`LoopHandle::insert_source`](https://docs.rs/calloop/0.7.0/calloop/struct.LoopHandle.html#method.insert_source)), but winit doesn't have the user callback until after the `calloop::EventLoop` is initialized, once `EventLoop::run` is called. Previously, when the X11 backend was using `calloop`, it would use the source callback to read X events and push processed winit events into a shared queue, which was then drained by the main loop. This is similar to how Wayland currently uses `calloop`, using the internal `WindowUpdate` structure to pass information from the source callback to the main loop.

It's possible that the X11 backend could be refactored to accept the `calloop` model, but I think it would take significant work and removing one dependency doesn't seem like a sufficient gain to justify that work.
