### ISSUE TITLE
[Windows] Building a new Fullscreen exclusive window creates undesirable visual artifacts. 

### ISSUE THREAD

**Issue by antonmarsden** [rust-windowing/winit#1536]
When creating a Window (on Windows) as per below, I notice that a white box on a black background appears, then some time later my event handler kicks in and handles a redraw event.
```
    WindowBuilder::new()
        .with_title(title)
        .with_fullscreen(Some(Fullscreen::Exclusive(videoMode)));
```
There is a workaround for this, but ideally the library should Just Work, and work pretty well :) The workaround is to add:
```
   .with_visible(false)
```
to the WindowBuilder, then call:
```
 window.set_visible(true)
```

On further investigation, it looks like WindowBuilder is triggering a request_redraw event on the Window, which may well be creating the white box on black background if the Window's default state is visible. Also note that if I use the above workaround then nothing will be drawn at all until the redraw event is processed by the event handler.

I'm not sure what the "right" approach is here in terms of redraw events, i.e.,
- should WindowBuilder be triggering a redraw event after Window creation if the window is not visible?
- should set_visible(true) trigger a redraw event?

More importantly, why is a white box and black background appearing at all? What is doing this redraw?

**Comment by antonmarsden** [comment]
May well be fixed by #1496, but I have yet to test it.

**Comment by alexheretic** [comment]
I'm using a much worse workaround for the white box issue in Robo Instructus, setting the window size to very small then re-sizing ...I get a smaller white box. I'll need to try this workaround.

**Comment by Osspial** [comment]
Hi, and thanks for opening this issue!

This is the expected behavior. Windows initializes new windows with unspecified image data, and will display said data if the application doesn't render anything to the window by the time the OS is ready to present the window to the user. You'll actually see that same data in the window if you run any of Winit's examples, since none of those ever render anything to the window. I'd expect this to happen on most desktop systems (except those running Wayland, since Wayland is weird), so the technique you've described is most likely necessary everywhere.

Still, it *is* somewhat surprising behavior, so the documentation should make that explicit. I've made a PR to add that information in - could you do a quick check over #1541 to make sure it seems clear to you?

**Comment by antonmarsden** [comment]
> I'm using a much worse workaround for the white box issue in Robo Instructus, setting the window size to very small then re-sizing ...I get a smaller white box. I'll need to try this workaround.

I've ended up with something like this, which is a bit long-winded, but makes the window visible once the event loop kicks in:
``
    window = ...
    ...
    let mut first_run = true;

    event_loop.run(move |event, _, control_flow| {
        
        if first_run {
            window.set_visible(true);
            first_run = false;
        }
``

Perhaps a simpler approach is sufficient?
``
    window = ...
    ...
    window.set_visible(true);
    event_loop.run(move |event, _, control_flow| {
        ...
``
