### ISSUE TITLE
EventLoop::run method's  callback with `'static` bounds

### ISSUE THREAD

**Issue by M-Adoo** [rust-windowing/winit#1543]
I found the `event_handler` in `EventLoop::run` is bounds with `'static`,  seems it's not necessary.  The  below simple demo is not work:

```rust
struct App<'a> {}

impl<'a> App<'a> {
  pub fn run(self) {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| {
      // can not capture `self`, because is not 'static.
      self.do_something()
    })
  }
}
```
I think is should be work, because `App` is outlive `event_loop`,  is there something I didn't understand?

**Comment by Osspial** [comment]
Hi, and thanks for the question!

`event_handler` needs to be `'static` because some platforms (WASM, mainly) destroy the stack before the event loop closure gets executed. If your program only needs to run on the desktop you can use the [`run_return`](https://docs.rs/winit/0.22.1/winit/platform/desktop/trait.EventLoopExtDesktop.html#tymethod.run_return) method to run the event loop, which doesn't require a '`static` bound.

**Comment by M-Adoo** [comment]
Thanks, I get it.

**Comment by M-Adoo** [comment]
If `event_handler` is live longer than `event_loop`  rather than `static`, will it work ?

**Comment by Osspial** [comment]
Nope, it has to be `'static`.
