### ISSUE TITLE
`available_monitors` on EventLoopWindowTarget

### ISSUE THREAD

**Issue by AdminXVII** [rust-windowing/winit#1566]
Issue: You can't list monitors unless you already have a window open and/or you're outside the event loop. I've a project where I want to spawn a window on each monitor periodically, then close them. The problem is that `available_monitors` is implemented only on EventLoop, not on the subset found inside the `run` closure.

I currently have a workaround where I spawn a window that I hide for the duration of the program and use it only to list monitors. However, I find this hacky at best and I think there could be a better solution.

Proposition: move `available_monitors` to EventLoopWindowTarget, so that it's available inside the `run` closure. I believe if it's possible on window inside the event loop, it should also be possible.

I don't have experience with the codebase, but if it is relatively beginner-friendly and with a bit of guidance I should be able to roll out a PR. Please let me know if that seems a good option.

If there is something that I overlooked, please let me know.

**Comment by Osspial** [comment]
This seems like a sensible change to me. If you could pull together a PR for this, that'd be great! The codebase should be fairly easy to navigate - the public cross-platform API surface is exposed in the root-level `src/*.rs` files, and the platform-specific function implementations live in the `src/platform_impl/$platform/**.rs` files. The biggest obstacle for implementing this sort of change is making sure it compiles everywhere, since it's non-trivial to build Winit on all the platforms it supports, but we've got a fairly quick-to-respond CI system set up so you should be able to check that to fix errors that crop up on platforms you can't compile yourself.

Implementing this mostly be a matter of moving the `available_monitors` function from the `EventLoop` impl to the `EventLoopWindowTarget` impl, and updating any field accesses necessary to make those compile.
