### ISSUE TITLE
`raw_window_handle`

### ISSUE THREAD

**Issue by kulicuu** [rust-windowing/winit#1567]
I'm working with a Vulkan wrapper crate called Ash and apparently there used to be a `winit::Window.get_hwnd()` but now that function is not in the current version.  I noticed `Window` is now in `winit::window::Window`, and there is a trait yielding function `raw_window_handle` but compiler returns error saying this function is not on winit::window::Window`

I've noticed now there is a library `raw-window-handle`, and I will be looking into --hopefully up to date versions -- of the winit examples to get a better idea of best ways to do this stuff.  Latest verisons of everything, Rust nightly.  
winit 0.22.1
ash 0.31.0
winapi 0.3.8

OS: Windows 10

**Comment by tangmi** [comment]
I think the intention is to have your library consume `raw_window_handle::HasRawWindowHandle` (which `winit::Window` is), then match on the resulting `raw_window_handle::RawWindowHandle`:

```rust
// Note this code doesn't need to know about winit directly!
fn get_hwnd(has_raw_window_handle: impl raw_window_handle::RawWindowHandle) -> HWND {
  match has_raw_window_handle.raw_window_handle() {
    raw_window_handle::RawWindowHandle::Windows(windows_handle) => windows_handle.hwnd,

    // If you'd like to handle other operating system's window handles, you can match on other `RawWindowHandle` variants.
    _ => panic!("unsupported os"),
  }
}
```

At first glance, this seems a lot more clunky than what was previously there, but it lets the rust-windowing and gfx-rs ecosystems iterate without codepending on specific versions of each other and allows compatibility with external, unrelated libraries.

**Comment by Osspial** [comment]
@tangmi's answer is largely correct - for public APIs, you should probably consume an `impl HasRawWindowHandle` instead of a Winit window, if all you're doing is retrieving a HWND. However, it's worth noting that the HWND retrieval method still exists, it's just that we removed the `get_` prefix from Winit getter functions to better follow Rust API best practices. It's now exposed as just [`hwnd()`](https://docs.rs/winit/0.22.2/x86_64-pc-windows-msvc/winit/platform/windows/trait.WindowExtWindows.html#tymethod.hwnd).
