### ISSUE TITLE
Fullscreen state and restore size not tracked correctly on GNOME Wayland

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1601]
It seems like there are two problems with fullscreen on GNOME Wayland:
 - The first set_fullscreen is ignored, it is required to set it to false and then true again to make it work
 - When leaving fullscreen mode, the original window size is not restored

This does not happen when the decorations are disabled, only with the decorations active.

Maybe this is a bug in GNOME with how winit decorations are handled?

It was originally reported to Alacritty in https://github.com/alacritty/alacritty/issues/3831.

**Comment by kchibisov** [comment]
IIRC it worked at some point, but after some magic GNOME update it got borken(I swear this code was tested on some old GNOME in the past, since it was likely from me). It seems to be related to the decorations hiding and resizing ordering, etc. It'll anyway require sctk update first, since fixing without it will be a pain.
