### ISSUE TITLE
Wrong virtual keycode in WindowEvent from Alt key while holding Shift on X11

### ISSUE THREAD

**Issue by Bakutomo** [rust-windowing/winit#1656]
### Platform:
X11 on Linux

### Steps to reproduce:
1. `cargo run --example window | grep KeyboardInput`
2. hold either shift key down
3. press or release the alt key

### Expected result:
A `WindowEvent` with `virtual_keycode: Some(LAlt)`

### Actual result:
A `WindowEvent` with `virtual_keycode: None`

The below output is from the input sequence:
press LShift, press LAlt, release LShift, release LAlt
```
DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: (empty) }) }
WindowEvent { window_id: WindowId(X(WindowId(117440513))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: SHIFT }, is_synthetic: false } }

DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: SHIFT }) }
WindowEvent { window_id: WindowId(X(WindowId(117440513))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: None, modifiers: SHIFT | ALT }, is_synthetic: false } }

DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: SHIFT | ALT }) }
WindowEvent { window_id: WindowId(X(WindowId(117440513))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: ALT }, is_synthetic: false } }

DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }) }
WindowEvent { window_id: WindowId(X(WindowId(117440513))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }
```

Note that the `virtual_keycode` in `DeviceEvent` is correct. Only `WindowEvent` is affected. The same problem also happens if I hold RShift instead of LShift.

**Comment by murarth** [comment]
The root cause of the problem is simple: On X11, winit uses an X `KeySym` value to determine which `VirtualKeyCode` to assign. X tells winit that the Alt key has a different keysym value when the Shift modifier is set. (Modifier state is not taken into account for `DeviceEvent` keysym lookup, which is why the virtual keycode is accurate for device events.)

Unfortunately, the solution is not so simple. winit could translate Shift+Alt keysyms to `LAlt` and `RAlt`, but I'm not sure whether that would be accurate for every possible environment. (These keysyms correspond to `XK_Meta_L` and `XK_Meta_R` on my system.)

Alternatively, winit could ignore modifier state altogether when assigning a key event's virtual keycode, but this has wider implications. There was some discussion on #812 about changing how winit determines virtual keycode, but it seems that no conclusions were reached.

**Comment by alice-i-cecile** [comment]
Reproduced in https://github.com/Leafwing-Studios/Emergence/issues/342.

**Comment by kchibisov** [comment]
not an issue anymore iirc.
