### ISSUE TITLE
Cross platfrom mouse button translation

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/winit#1785]
Right now winit only provides translation for `Left`, `Right`, and `Middle,` mouse buttons and everything else is via `Other`, however each platform defines their own value for other for the same buttons, it'll be nice to agree and extend  `MouseButton` enum to include extra mouse buttons as well.

**Comment by maroider** [comment]
It would probably be uncontroversial to include the `Forward` and `Back` buttons.
I'm not sure what other "common" buttons exist.

**Comment by kchibisov** [comment]
Yeah, I also think that we can include those, I just know that there are mices with something like numpad right on them, though, I have no clue how they are identified.

**Comment by maroider** [comment]
> I just know that there are mices with something like numpad right on them

The only mice that I know of with such features are "gaming" mice. Presumably, they don't directly expose these extra buttons as generic mouse buttons, but instead have some software component (like Razer Synapse) translate them into whatever is configured by the user. It could also be the case that the mouse presents itself to the operating system as both a mouse and a keyboard.

In particular, the "Razer Naga Trinity" and "Razer Naga Chroma" seem to match what you've described.

**Comment by dhardy** [comment]
> It could also be the case that the mouse presents itself to the operating system as both a mouse and a keyboard.

I've certainly seen this behaviour (also for keyboards).

The most "standard" buttons a mouse might have would be left/right/middle, scroll up/down/left/right, and two left and two right buttons. However I don't think there's an OS standard beyond Back/Forward.

**Comment by maroider** [comment]
There are admittedly two other "buttons" which seem to be semi-standard: tilting the scroll wheel left and right, but these "buttons" seem to either emulate a horizontal scroll wheel or the "forward" and "back" buttons.

**Comment by chrisduerr** [comment]
@kchibisov Which platform differences are you aware of? I know for example that the "backward" button in X11 is 8, so there seems to be quite a lot of distance between RMB and that.

I'm also not sure if this is consistent across mice? But I'd hope so at least.

**Comment by kchibisov** [comment]
On Wayland those are 0x113 and 0x114, since they Wayland just forwards kernel buttons. On X11 they are indeed 8 and 9. Web right now uses some other stuff, and macOS, I bet, do something else as well.

**Comment by chrisduerr** [comment]
Seems like the only option would be to have actual constants/enum values for all the buttons and painfully mapping every single one of them.

**Comment by maroider** [comment]
> I know for example that the "backward" button in X11 is 8, so there seems to be quite a lot of distance between RMB and that.

I wasn't actually actively looking out for this, but I stumbled onto this while dealing with `XkbStateNotify`.
It seems like the following values and "buttons" are used/available on X11, at least with the mouse I tried.

| Button              | Value |
| ------------------- | ----- |
| Left mouse button   | 1     |
| Middle mouse button | 2     |
| Right mouse button  | 3     |
| Mouse wheel up      | 4     |
| Mouse wheel down    | 5     |
| Mouse wheel left    | 6     |
| Mouse wheel right   | 7     |
| Back                | 8     |
| Forward             | 9     |

I was admittedly a little surprised to see these "mouse wheel" buttons, which look like they correspond to moving the mouse wheel one by one "ratchet".

I think this behaviour may also be available/implementable in some form on Windows, as I recall reading that some people would re-bind the jump key in Counter Strike to the mouse wheel in order to bhop (bunny hop) (see "mwheeldown" and "mwheelup" on the [Valve Developer Community (wiki)](https://developer.valvesoftware.com/wiki/Bind).
