### ISSUE TITLE
Windows: Mouse capture not released in some cases

### ISSUE THREAD

**Issue by SamRodri** [rust-windowing/winit#1796]
To enter the incorrect state:

1 - Run one of the window examples.
2 - Press a mouse button in the window content.
3 - Press ALT+TAB to focus another window.
4 - Release the mouse button.
5 - Focus the example window again.
6 - Press and release a mouse button in the window content.

After these steps it is not possible to click the window close button because the mouse is captured.

**Comment by maroider** [comment]
I've managed to reproduce this with quite a few of the examples (even `fullscreen`, since this `SetFocus` also disables <kbd>Alt</kbd>+<kbd>F4</kbd>).

There were some minor issues with the reproduction steps:
- (4) must not be done while the cursor is over a non-obscured portion of the client area of the Winit window.
- (5) must not be accomplished by clicking inside the client area.

This was otherwise a straightforward bug to trigger.
