### ISSUE TITLE
Remove SCTK on Wayland and migrate to wayland-client

### ISSUE THREAD

**Issue by alula** [rust-windowing/winit#1802]
`smithay-client-toolkit` pulls a lot of trash dependencies that most applications do not use or ever need.

Seems like there was an implementation based on `wayland-client` crate, but for some reason the wayland backend migrated to sctk: 1e971030946a289eec598c0c40bff6ec8ba1190f

```
│   │       ├── smithay-client-toolkit v0.12.0
│   │       │   ├── andrew v0.3.0
│   │       │   │   ├── bitflags v1.2.1
│   │       │   │   ├── line_drawing v0.8.0
│   │       │   │   │   └── num-traits v0.1.43
│   │       │   │   │       └── num-traits v0.2.12 (*)
│   │       │   │   ├── rusttype v0.9.2
│   │       │   │   │   ├── ab_glyph_rasterizer v0.1.3
│   │       │   │   │   └── owned_ttf_parser v0.6.0
│   │       │   │   │       └── ttf-parser v0.6.2
│   │       │   │   ├── walkdir v2.3.1
│   │       │   │   │   └── same-file v1.0.6
│   │       │   │   ├── xdg v2.2.0
│   │       │   │   └── xml-rs v0.8.3
│   │       │   ├── bitflags v1.2.1
│   │       │   ├── byteorder v1.3.4
│   │       │   ├── calloop v0.6.4
│   │       │   │   ├── log v0.4.11 (*)
│   │       │   │   └── nix v0.18.0 (*)
│   │       │   ├── dlib v0.4.2 (*)
│   │       │   ├── lazy_static v1.4.0
│   │       │   ├── log v0.4.11 (*)
│   │       │   ├── memmap v0.7.0
│   │       │   │   └── libc v0.2.74
│   │       │   ├── nix v0.18.0 (*)
│   │       │   ├── wayland-client v0.28.0 (*)
│   │       │   ├── wayland-cursor v0.28.0
│   │       │   │   ├── nix v0.18.0 (*)
│   │       │   │   ├── wayland-client v0.28.0 (*)
│   │       │   │   └── xcursor v0.3.2
│   │       │   │       └── nom v5.1.2
│   │       │   │           └── memchr v2.3.3
│   │       │   │           [build-dependencies]
│   │       │   │           └── version_check v0.9.2
│   │       │   └── wayland-protocols v0.28.0
│   │       │       ├── bitflags v1.2.1
│   │       │       ├── wayland-client v0.28.0 (*)
│   │       │       └── wayland-commons v0.28.0 (*)
│   │       │       [build-dependencies]
│   │       │       └── wayland-scanner v0.28.0 (*)
```

**Comment by kchibisov** [comment]
smithay-client-toolkit is essential crate that provides all the needed dependencies to implement proper support for Wayland, if you want to reduce the amount of dependencies we're using for Wayland, bring it to smithay-client-toolkit.

Just to elaborate.

You need to do the following to support Wayland properly:

- Draw cursor(wayland-cursor crate)
- Draw window decorations (andrew and font drawing stuff in it)
- Load libxkbcommon other stuff (dlib, etc)
- Provide event loop integration(calloop) and calloop is used in winit for event loop
- Provide custom protocols, via wayland-protocols, since some of them are used by winit

So you won't remove anything by removing smithay-client-toolkit, you'll just bring this mess right in winit.

**Comment by kchibisov** [comment]
If you have concerns about decorations drawing crates, like andrew, bring it to smithay-client-toolkit, but those crates are pretty small, though, font loading should be reworked imho.
