### ISSUE TITLE
Finding new maintainers

### ISSUE THREAD

**Issue by ArturKovacs** [rust-windowing/winit#1940]
As shown in the [testers and contributors table](https://github.com/rust-windowing/winit/wiki/Testers-and-Contributors), currently there's no maintainer for X11, Wayland, and the Web. Needless to say this makes it difficult to address issues and merge PRs involving those platforms. We need at least one maintainer for every platform.

The question is how to find a suitable maintainer. In my view the requirements for a maintainer is to: be kind, have time for it, have experience in Rust, and be motivated to maintain the platform.

@coderedart brought up in the matrix room, that we could ask for a maintainer on Reddit or Discord. I think this is not a bad idea, but I'm just worried there may be multiple people suddenly showing up and picking one seems like a stressful thing to me. What are your thoughts @maroider, @francesca64, @msiglreith?

**Comment by FuriouZz** [comment]
Hello @ArturKovacs ! I am mainly a web developer who have some experiences in Rust. I worked on winit last year on the [gamepad implementation](https://github.com/rust-windowing/winit/pull/1414). I will be glad to help.

**Comment by maroider** [comment]
> I will be glad to help mainly on the wasm backend.

I'm glad to see that you want to help out :), but let's keep this issue focused on discussing a strategy for attracting and on-boarding new maintainers.

---

# Advertising

> we could ask for a maintainer on Reddit or Discord

In terms of advertising the vacancies, I think we should cast a wide net as possible. The following channels may be reasonable places to advertise:

- Discord Servers
  - Rust Programming Language Community Server
  - Game Development in Rust
    - Maybe do a short segment on the monthly meetup?
  - Amethyst
  - Bevy Engine
  - Veloren Community
- Reddit
  - r/rust
  - r/rust_gamedev (most users are probably also subbed to r/rust)
- Newsletters
  - [This month in Rust GameDev](https://gamedev.rs/)
  - [This week in Rust](https://this-week-in-rust.org/)

In particular, I hope we can get some regular contributions from Bevy and Veloren, as both projects have a solid number of contributors.

There are already two other issues on the issue tracker about the maintainership of Wayland (#1777) and WASM (#972).

# On-boarding

> I'm just worried there may be multiple people suddenly showing up and picking one seems like a stressful thing to me

I don't think we should outright "pick" new maintainers from the get-go. I believe it is best that the maintainers we end up with are willing, motivated and able to address issues and review PRs in a timely manner, and merely saying "I want to be a maintainer" is hardly enough to convince me that someone is *actually* fit to be a maintainer. Instead, I think we should:
1. Bring interested parties on board as contributors.
2. Someone (probably me, tbh) will then ping them in issues and PRs affecting platforms said contributors have marked themselves as "interested" in.
3. Those that stick around, review PRs, and are otherwise excellent contributors can then be promoted to maintainers, if they so desire. 

# Non-maintainer roles

I think it's also a good idea to ask people if they'd be willing to be merely be available to answer questions that may come up about certain platforms, i.e. the `Expert` role in the "[Testers and Contributors](https://github.com/rust-windowing/winit/wiki/Testers-and-Contributors)" table. Having easy access to people who can answer platform-specific questions would potentially be a lot more efficient than always having to figure things out on our own.

**Comment by francesca64** [comment]
@maroider thanks for saying all the good ideas so that I don't have to do anything.

**Comment by dhardy** [comment]
> In terms of advertising the vacancies, I think we should cast a wide net as possible.

Maybe that helps, maybe not. My experience is that interested people tend to stumble on the project anyway — winit already has plenty of users. Perhaps though advertising through the major dependants (I guess the game engines + iced) may help.

I'm sure there are also plenty of people (like myself) reading the project pages but mostly staying quiet.

In terms of on-boarding, perhaps it would help to:

1.  have a place where new-comers can introduce themselves and ask questions (I guess that's what the three IM boards are for, though not everyone uses those; a permanently-open issue may also help)
2.  have a jobs-board, e.g. asking someone familiar with X11 to review PR ###

**Comment by ArturKovacs** [comment]
For some reason I thought that we would need to immediately memberize some of those who respond to our advertisement. Which would not be a good idea, so I really like the approach that @maroider laid out - we invite people, then those who are active in winit and show promise, are offered to get memberized.

There seems to be consensus that we should advertise in those communities that currently depend on winit. @maroider do you mind doing so? The game related ones seem like a good start. Otherwise I can do it.

**Comment by maroider** [comment]
> My experience is that interested people tend to stumble on the project anyway

Yeah, that's how I ended up here at least :)

I'm not really expecting a lot of people to end up becoming contributors, but my hope is that by casting "a wide net", we'll (maybe) end up with a couple more contributors who might otherwise not have joined us.

Major dependants, as you mentioned, are probably the place we're we'll see the most engagement (if any).

> I'm sure there are also plenty of people (like myself) reading the project pages but mostly staying quiet.

I agree, but this is also something that's hard to get a good read on.

> My 2c from maintaining `rand`: sometimes just asking someone who's already stopped by if they'd like to make a PR or review X can work.
> * have a place where new-comers can introduce themselves and ask questions (I guess that's what the three IM boards are for, though not everyone uses those; a permanently-open issue may also help)
> * have a jobs-board, e.g. asking someone familiar with X11 to review PR ###

I think that having a permanently-open on-boarding issue might be helpful, but I'm not sure what a "jobs-board" would look like.

In a similar vein to these suggestions: it might be useful to enable GitHub's new(-ish) "Discussion" feature on this repository as another way to "contact the Winit folks".

**Comment by maroider** [comment]
> There seems to be consensus that we should advertise in those communities that currently depend on winit. @maroider do you mind doing so? The game related ones seem like a good start. Otherwise I can do it.

Sure, I can handle that. I probably won't get to it this week, but I'll see what I can do next week.

**Comment by kchibisov** [comment]
>currently there's no maintainer for X11, Wayland

Well, I'm technically still a Wayland maintainer, and I've left winit to @vberger for the time I wouldn't have time to work on it (and other things). However, I have an opportunity to work on things from time to time, so

**Comment by maroider** [comment]
> Well, I'm technically still a Wayland maintainer

I'm glad to see that you're still alive and interested in contributing, @kchibisov.
With that in mind, I've pre-emptively re-added you to [the table](https://github.com/rust-windowing/winit/wiki/Testers-and-Contributors).

> and I've left winit to @vberger for the time I wouldn't have time to work on it (and other things).

Was this communicated somewhere? I can't recall seeing this written anywhere.

**Comment by kchibisov** [comment]
>   I'm glad to see that you're still alive and interested in contributing,

I'm glad that I'm still alive too, I just haven't had physical access to any PC for like 6 month, so was a bit hard to contribute (I can still disappear for the rest 6 month though).

 >Was this communicated somewhere? I can't recall seeing this written anywhere.

it was done on matrix with @vberger , since he was maintaining Wayland in the past and helped a lot with sctk and rust + Wayland infra.

**Comment by maroider** [comment]
Welp, it took me longer than I'd like to get around to actually doing something, but I've [submitted a PR](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/679) for a section on the *This month in Rust GameDev* newsletter advertising our need for helping hands.

**Comment by madsmtm** [comment]
So, uh, happy holidays, I've been here for a while and have somehow ended up configuring my watch settings to "All activity" :grin:. I got the [kind offer](https://github.com/rust-windowing/winit/pull/1759#issuecomment-792321210) (still sorry about not having gotten that PR through!) to become a maintainer a while ago, but turned it down because I didn't feel like I was ready to take on that responsibility.

I think I am now, so I'll be glad to take on the role as macOS maintainer for at least the coming 6 months, if you'll have me! It should be noted that I'm a student, so won't have that much time, and I'm mostly doing this because I want to, there is not a higher purpose for me (like actually developing a useful application using `winit`. Yet, at least).

<sub>I'm doing this now to prevent it from turning in to a bad new year's promise that I won't keep :wink:</sub>

**Comment by francesca64** [comment]
@madsmtm thanks so much, and we're glad to have you! Invite sent.

**Comment by kchibisov** [comment]
I'll close this issue. Maintainers will be naturally picked by the time they spent fighting winit and establishing the required 'trust' level with the rest maintainers.
