### ISSUE TITLE
[X11] Missing key release event

### ISSUE THREAD

**Issue by Voodlaz** [rust-windowing/winit#1965]
So, our engine uses winit for windowing, and have encoutared this issues: https://github.com/rg3dengine/rg3d/issues/108

What can cause this issue? A bug in winit or bug in the engine? The issue have some information too, look at the disscussion in the issue.

**Comment by maroider** [comment]
From the issue you linked, it seems like the problem you're having *looks* like it's caused by a missing key release event, and I've changed the issue title to reflect that.

I'm going to need some more info in order to get a proper understanding of *exactly* what's going wrong, though.
- Are you using `WindowEvent` or are you using `DeviceEvent`?
- Does the issue only occur with a single key (e.g. only <kbd>A</kbd> or <kbd>B</kbd>), or are multiple keys affected?
- What does resizing the window have to do with your issue?
- Can you reproduce it with Winit only?
- Can you reproduce it with my `new-keyboard-linux` (#1932) branch?

**Comment by Voodlaz** [comment]
- We use `WindowEvent`. It seems that there was some [issue with inputting](https://github.com/rg3dengine/rg3d/issues/32) which made us switch from `DeviceEvent` to `WindowEvent`.
- no, it isn't tied
- there's no issues if the window hasn't been resized. 
- [I haven't done it yet, will update my comment]
- I, uhh, couldn't figure how to do it.

**Comment by Voodlaz** [comment]
@maroider what is the replacement for VirtualKeyCode in the new version?

**Comment by maroider** [comment]
Its closest analogue is the `Key` enum, but it's not quite the same (and for good reason).

**Comment by Voodlaz** [comment]
Well, we use VirtualKeyCode Event, so will Key enum easy replace it?

**Comment by Voodlaz** [comment]
@maroider I suggest we better do it in matrix chat.

**Comment by Voodlaz** [comment]
@maroider what example I should choose for trying to reproducing this bug in winit only?

**Comment by maroider** [comment]
Ideally, you'd make your own minimal, reproducible example based off of the keyboard handling code in rg3d.
