### ISSUE TITLE
`Event::LoopDestroyed` not always emmited 

### ISSUE THREAD

**Issue by emilk** [rust-windowing/winit#1998]
On Mac, when I press Cmd+Q the window closes, but there is no `Event::LoopDestroyed` emitted, so I cannot save my program state.

winit version: 0.25.0, used via glium/glutin.

**Comment by tinaun** [comment]
I think this can be fixed by overriding `applicationWillTerminate:` to send a LoopDestroyed event in winits appdelegate

**Comment by madsmtm** [comment]
Huh, this changed in #1583 when a default macOS menu was added, because as it registers the `Quit {process_name}`, it also registers the key combination for it. It was even pointed out here: https://github.com/rust-windowing/winit/pull/1583#issuecomment-731645563, sorry it slipped past the changelog!

**Comment by madsmtm** [comment]
An alternative to the proposed PR would be to use the `stop:` selector in `menu.rs` instead of `terminate:`; this would allow `run_return` to resume, if I'm not mistaken? And the teardown code [after `[app run]`](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/macos/event_loop.rs#L174-L183) would be called properly.

Though I don't really have a preference
