### ISSUE TITLE
Can wayland `dlopen` feature be optional?

### ISSUE THREAD

**Issue by Riey** [rust-windowing/winit#2037]
Currently `wayland-client` and `sctk` use `dlopen` feature to link with system wayland library

but I want static version for dependency problem and preferred Rust implementation

**Comment by kchibisov** [comment]
Do you want pure rust sctk + wayland impl? If that's the case this is not what I'd support, since it doesn't make much sense right now, due to its limitations (you can't use OpenGL other rendering libs with it). As for linking to libxkbcommon, libwayland-client during linking executable rather than doing dlopen I think it's fine to add such feature, since sctk exposes it, though dlopen is handy when it comes to compiling with support for both x11 and wayland at the same time without requiring those libraries to be installed.

**Comment by Riey** [comment]
> Do you want pure rust sctk + wayland impl? If that's the case this is not what I'd support, since it doesn't make much sense right now, due to its limitations (you can't use OpenGL other rendering libs with it). As for linking to libxkbcommon, libwayland-client during linking executable rather than doing dlopen I think it's fine to add such feature, since sctk exposes it, though dlopen is handy when it comes to compiling with support for both x11 and wayland at the same time without requiring those libraries to be installed.

I see, but I want this feature even with system-lib because `dlopen` doesn't work well on some platform like NixOS since this distro don't have `system-lib` so winit apps need either `rpath` or `LD_LIBRARY_PATH` right now :confused:

**Comment by kchibisov** [comment]
Yeah, for that part I've already sent a patch. Look at linked PR.
