### ISSUE TITLE
Should not request for redraw when window is closed

### ISSUE THREAD

**Issue by lessneek** [rust-windowing/winit#2049]
I got a panic error on window close in any nannou app.
We should check if window is closed and do not send a redraw request.
In the https://github.com/rust-windowing/winit/blob/ed698f2462467cc8b9a178238baeef5bb32a19d5/src/platform_impl/linux/wayland/event_loop/mod.rs#L393
need to extend the condition like this: `if window_update.redraw_requested && !window_update.close_window`
it works for me, no panic on close now.
What do you think? May my fix causes some other problems?

**Comment by kchibisov** [comment]
@lessneek Could you share what sort of panic do you have?

The thing is that API is correct, since the close is just requested and you can safely ignore it. So I don't see any issue in the current code, since the window is present. On close requested you can prompt user whether they want to e.g. save changes ignoring close.

**Comment by kchibisov** [comment]
Fixed as a part of 2496098 .
