### ISSUE TITLE
How to detect multiple keys pressed at the same time?

### ISSUE THREAD

**Issue by fochive00** [rust-windowing/winit#2075]
Hi, I'm new to winit and I'm having some problems.

For example, I want to implement a 3D camera, and I want to change the camera position with  W, A, S, D keys.

I use match statement like this:
`*control_flow = winit::event_loop::ControlFlow::Poll;`
...
![image](https://user-images.githubusercontent.com/42891884/143666526-84a8497a-4a4c-4095-aacd-29721aad65d7.png)

An `Event` contains only one `virtual_keycode`. When I press two keys at the same time, only one key works. I looked through the documents and thought hard, but I couldn't find a solution. What am I going to do?

Thank you for your help!

**Comment by msiglreith** [comment]
Hello, typically, this is handled via a hashmap (`VirtualKeyCode`:`ElementState`) and the actual camera update happens only after `MainEventsCleared` or on `RedrawRequested` (depending on where you update your game state). This allows to have a consistent state of all current keypresses and handles key repeat events as well, otherwise the camera might stutter.

Example: https://github.com/msiglreith/glace/blob/a3240905f7d8c5ffc918b25e34ce048f279371e2/glacier/examples/pathtrace.rs#L687-L736

**Comment by fochive00** [comment]
> Hello, typically, this is handled via a hashmap (`VirtualKeyCode`:`ElementState`) and the actual camera update happens only after `MainEventsCleared` or on `RedrawRequested` (depending on where you update your game state). This allows to have a consistent state of all current keypresses and handles key repeat events as well, otherwise the camera might stutter.
> 
> Example: https://github.com/msiglreith/glace/blob/a3240905f7d8c5ffc918b25e34ce048f279371e2/glacier/examples/pathtrace.rs#L687-L736

Thank you for your reply. I will take a closer look at the example you provided.
