### ISSUE TITLE
Compiling on Windows failed

### ISSUE THREAD

**Issue by jinleili** [rust-windowing/winit#2198]
Platform: M1 Mac + Parallels Desktop 17 + Windows 11(installed VS 2019 C++ Tools)

```sh
  Compiling winit v0.26.1 (C:\Users\lijinlei\Rust\winit-master)
error[E0432]: unresolved import `crate::platform_impl::platform::event_loop::WindowLongPtr`
  --> src\platform_impl\windows\window.rs:44:51
   |
44 |         event_loop::{self, EventLoopWindowTarget, WindowLongPtr, DESTROY_MSG_ID},
   |                                                   ^^^^^^^^^^^^^ no `WindowLongPtr` in `platform_impl::platform::event_loop`

error[E0412]: cannot find type `WindowLongPtr` in this scope
   --> src\platform_impl\windows\event_loop.rs:654:58
    |
654 |             (winuser::WS_VISIBLE | winuser::WS_POPUP) as WindowLongPtr,
    |                                                          ^^^^^^^^^^^^^ not found in this scope   

error[E0412]: cannot find type `WindowLongPtr` in this scope
   --> src\platform_impl\windows\event_loop.rs:676:26
    |
676 |             input_ptr as WindowLongPtr,
    |                          ^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0412, E0432.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `winit` due to 3 previous errors
```

**Comment by maroider** [comment]
Welp, that's somewhat embarrasing. I assume you're compiling for one of the ARM target triples (idk which one is correct for macOS). The issue is that the type of [`WindowLongPtr`](https://github.com/rust-windowing/winit/blob/f3f6f1008a5891ed0c9e5e8f26568f8f2d49f164/src/platform_impl/windows/event_loop.rs#L791-L794) is controlled by `cfg` guards, but only for `target_arch = "x86"` and `target_arch = "x86_64"`. We should probably have been using `target_pointer_width` instead.

**Comment by msiglreith** [comment]
The parts causing the build issues have been replaced as part of the `window-sys` migration - it builds now correctly when cross compiling from a window system. Not sure if it's worth adding a CI check as it would say it's rather lower tier platform
