### ISSUE TITLE
Allow window to be a child of an existing NSView on Mac OS

### ISSUE THREAD

**Issue by glowcoil** [rust-windowing/winit#220]
I'm interested in adding this functionality to winit. My use case is writing cross-platform VST audio plugins; I would like to use winit and glutin to keep the platform-specific code to a minimum, but currently I'm unable to use them on Mac OS as the VST host creates a window for me and the API just hands me an NSView.

I've looked into adding this via the platform-specific builder. It would require a different way of event handling than using a window delegate, some functionality (such as setting the window title) would be unavailable or a no-op, and there would be a lot of branching based on whether we have an NSWindow or just an NSView. It seems doable, but I wanted to hear opinions on whether this is the right approach for winit.

**Comment by robsaunders** [comment]
I've modified winit already to do this, but it is an older version (0.5.x).

https://github.com/robsaunders/winit-vst

It's a fairly sloppy port but it works, I'm porting the newer version now though but the api has changed so just updating it. I sincerely doubt that winit will support this as the mac module had to be entirely re-written, it's not as simple as the windows equivalent. I can go into detail as to why if you need, but it wasted weeks of my time trying to work out a way that wouldn't require a complete re-write, and it's not a good fit due to the way hosts control the window (creating their own delegate already) and how cocoa works.

I am working on various vst gui projects and it might save you a lot of time to look over my github. I've gotten a few gui libs working and I've successfully ported conrod, but since decided conrod is really poorly written and not suited so I'm looking at new options.

Hope this saves you some time.

**Comment by micahjohnston** [comment]
Thank you for all the information! I ended up deciding that my own GUI layer was the best option. So far I have OSX working, but I'm planning to extend to Windows and Linux. I will probably pull it out into a really small library (not as flexible as Glutin and Winit) for using OpenGL with VSTs.

**Comment by robsaunders** [comment]
I concluded that too but I still use winit and glium on top of it. At the moment I'm just replacing conrod, and so far everything is sooooo much easier than trying to wrangle conrod into something usable. Are you going software or hardware accelerated?

**Comment by madsmtm** [comment]
`glutin` is now decoupled from `winit` using `raw-window-handle`, so you might be able to use that.

`winit` itself is not going to support being handed an arbitrary `NSView`/`NSWindow` and then work from there, we simply have too much state and delegate handlers on those for that to work (and have e.g. overridden `NSApplication` to fix various issues).
