### ISSUE TITLE
run_not_terminate

### ISSUE THREAD

**Issue by Yuri6037** [rust-windowing/winit#2256]
As discussed in the IRC, to use `winit` in my own 3D engine a function similar to run needs to be implemented. That function would return execution to the caller once the main loop is requested to exit instead of terminating the application without letting it a chance to properly terminate.

**Comment by Liamolucko** [comment]
You're basically describing [`EventLoop::run_return`](https://docs.rs/winit/latest/winit/platform/run_return/trait.EventLoopExtRunReturn.html#tymethod.run_return); it's not guaranteed to be available, though, because it's impossible to implement on some platforms (e.g. iOS).

If you just need it to clean things up, your best bet is probably to do it on [`Event::LoopDestroyed`](https://docs.rs/winit/latest/winit/event/enum.Event.html#variant.LoopDestroyed); I don't know the specifics of what you're doing, though.
