### ISSUE TITLE
when going through the learn-wgpu tutorial, error occured (windows 11, wsl2, ubuntu)

### ISSUE THREAD

**Issue by LollipopFt** [rust-windowing/winit#2377]
error: `[2022-07-17T03:51:11Z ERROR smithay_client_toolkit::window::fallback_frame] Failed to set cursor`

everything worked fine, it's just that this kept appearing on the terminal every time my mouse moved.

**Comment by kchibisov** [comment]
Seems like a wsl issue.

**Comment by LollipopFt** [comment]
i see, thanks!

**Comment by kchibisov** [comment]
I mean we'll keep it open for a while, until the answer will be clear. But maybe wsl isn't supporting all the linux features we're aiming for, like memfd, since it's something common on linux these days.

**Comment by LollipopFt** [comment]
i think it could be `winit` because `vkcube` and `gedit` works, even `lapce` editor does not have this problem.

**Comment by LollipopFt** [comment]
@kchibisov yeah

> everything works fine

it runs completely like it should, mouse actions are working just fine, just that in the terminal the error messages are appearing.

**Comment by kchibisov** [comment]
Well, the error is that it fails to set buffer for the cursor, most other applications probably ignored it. I think you may filter old it from the logs, if you use logger. Not sure if action should be performed here, given that the failure is fine. The problem is that it fails to set cursor icon, I'd assume you're using something from windows.
