### ISSUE TITLE
MouseScrollDelta::LineDelta x value always zero for Windows Touch Pad

### ISSUE THREAD

**Issue by markusmoenig** [rust-windowing/winit#2518]
MouseScrollDelta::LineDelta x value always zero for my Windows Touch Pad. Vertical works fine.

Other apps have working horizontal scrolling.

Note I am on v0.26 as this is the last version pixels works with.

**Comment by kchibisov** [comment]
Shouldn't your touchpad have pixel delta?

**Comment by markusmoenig** [comment]
No, it does not get called.

**Comment by msiglreith** [comment]
Probably related https://github.com/rust-windowing/winit/issues/2129
unfortunately trackpad drivers seem to be all over the place implementation wise

**Comment by markusmoenig** [comment]
Ok, thanks. Yes seems to be the same issue and it makes sense with the mixing of event types. Just worried that open issues and features do not get addressed here. Did everybody switch to Tao ?

**Comment by msiglreith** [comment]
> Just worried that open issues and features do not get addressed here

I'm currently listed as maintainer for the Windows backend in particular, but rather focus on trying to get pull requests merged in (with moderate sucess 😄) - therefore mostly relaying on external contribution for implementing new features due to lack of energy/time (except if I need it for myself for my own spare time project)
>  Did everybody switch to Tao ?
As far as I know `tao` is looking to gradually move back to `winit` once it reaches features parity. But overall the Rust ecosystem has multiple related crates focusing on one or the other aspect more (e.g druid-shell/glazier on UI, macroquad on games, etc). `winit` is somewhere in between I would say.

**Comment by markusmoenig** [comment]
Thanks for the answer!
