### ISSUE TITLE
directly support ibus

### ISSUE THREAD

**Issue by t18b219k** [rust-windowing/winit#2549]
FCITX and IBus have a same ibus interface so we can provide better IME event quality than XIM or Wayland text_input protocol.

**Comment by kchibisov** [comment]
What's wrong with Wayland text_input protocol? I don't really like the idea of having dbus to handle IME. Wayland protocol is widely supported and used by DEs as a sort of integration for OSK, etc.

**Comment by t18b219k** [comment]
Wayland is much better than XIM but IBus-Anthy or IBus-Mozc report not char boundary aware range reporting in IME::Preedit.

**Comment by kchibisov** [comment]
@t18b219k it's compositor job to convert if you're running old GNOME on Wayland you'll have that issue, modern compositors shouldn't have it or if they have it they should be patched, nothing. It's not like input is directly sent to text_input, the input is sent to compositor and then after compositor process it it is being send to Wayland client.

>but XIM on fcitx is not good

There's no desire to support ibus because of legacy X11 platform.

**Comment by t18b219k** [comment]
ok.
thank you about my question.
