### ISSUE TITLE
wayland: `RedrawRequested` isn't called while resizing window

### ISSUE THREAD

**Issue by ids1024** [rust-windowing/winit#2609]
On Wayland a `RedrawRequested` event isn't emitted until resizing ends. If an application is only drawing (for instance, with softbuffer) in response to `RedrawRequested` events, this is a problem, since the window doesn't visually change in size at all until we commit a buffer with the new size.

This seems to differ from the behavior on X or Windows, where the window does redraw during a resize.

I see `sctk::window::Event::Configure` is being produced throughout the resize, but this doesn't end up producing a `RedrawRequested` event from winit. Not sure exactly what should be changed for this to behave appropriately.

I've been testing this with https://github.com/rust-windowing/softbuffer/blob/master/examples/winit.rs, but removing the `request_redraw()` call for resize events, which I added there to make the example work properly on Wayland.

**Comment by kchibisov** [comment]
I can't repro that for example. For me I get the correct event each time I resize, but I test with glutin.

Maybe you don't return to the event loop, so it can read the queue or you drain the queue winit should read and the events are missed due to that?

It must produce a frame, if the size changed.

You can see the related logic in `window/mod.rs` and `event_loop/mod.rs`.

**Comment by kchibisov** [comment]
Nvm. Seems like it was indeed missing the call to ensure redraw.
