### ISSUE TITLE
IME support for mobile

### ISSUE THREAD

**Issue by hanxiaohuivc** [rust-windowing/winit#2766]
Excuse me, is there a plan to support IME on the mobile terminal?

**Comment by kchibisov** [comment]
Are you using Android/ios?

**Comment by rib** [comment]
I did start experimenting with enabling IME support in the android backend - and had a branch that was initially working with egui at least. Not sure if this was the latest state for that experiment but I have this old branch: https://github.com/rib/winit/tree/android-activity-ime-events

There is also this older android-activity branch where I started looking at this: https://github.com/rust-mobile/android-activity/tree/ime-support

I think in general the IME abstraction for Winit is roughly OK for Android too, but at least one notable difference is with the positioning of the IME UI. For a desktop OS / window system then the IME will generally be told the position of the text entry so that it can draw its completions next the the text entry but on mobile / Android then the virtual keyboard just pops up in a fixed location.

**Comment by rib** [comment]
It looks like I needed to add `begin_ime_input` and `end_ime_input` APIs for supporting Android - though I don't recall the details off the top of my head right now.

Here's the corresponding egui branch I had too: https://github.com/rib/egui/tree/android-winit-ime-support

**Comment by kchibisov** [comment]
>For a desktop OS / window system then the IME will generally be told the position of the text entry so that it can draw its completions next the the text entry but on mobile / Android then the virtual keyboard just pops up in a fixed location.

You can tie to `set_ime_allowed(bool)`, the api already here.

**Comment by rib** [comment]
thanks, yeah, I definitely knew about `set_ime_allowed` at the time and I'm fairly sure there was still a reason I added begin/end APIs but I don't recall why at the moment

**Comment by hanxiaohuivc** [comment]
@rib Thanks for your answer, I'll try it. Do you have a solution to support IME on ios? Will the IME-supported branch be merged into the stable release?

**Comment by rib** [comment]
Unfortunately I'm not familiar with what would be required on iOS, sorry.

At some point I'd like to revisit this branch for Android yep, or else others should also feel free to pick up the torch.

I imagine it should be possible to get merged without too much work yeah, the requirements are pretty similar other supported platforms.

**Comment by hanxiaohuivc** [comment]
@rib How to verify whether IME is supported after switching egui to android branch? Should I change the dependency on egui in an egui-based example (for example: https://github.com/inferrna/hello_world_android_egui) to the android branch? Thanks.

**Comment by rib** [comment]
Maybe take a look at these android examples for experimenting @hanxiaohuivc: https://github.com/rust-mobile/rust-android-examples

**Comment by hanxiaohuivc** [comment]
https://github.com/rust-mobile/rust-android-examples This example is very good and helped me a lot, thank you. @rib
