### ISSUE TITLE
Windows screen turns black

### ISSUE THREAD

**Issue by lethargy123** [rust-windowing/winit#2781]
When using the winit library in my code, I accidentally discovered a bug where scaling the window with the mouse causes black areas to appear on the window. Even when I scale it back to the size set in the code, there are still black areas present. After repeating this operation a few times, the window becomes entirely black.

**Comment by lethargy123** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/105811408/235335781-d901034a-85f0-42f6-9ff4-c8552fbdbfd1.png">
[just like this](javascript:;)

**Comment by notgull** [comment]
This is expected behavior if you don't draw anything into the window. `winit` intentionally avoids drawing anything to the window, with varying results depending on the OS. For Windows, this manifests as the initial area being colored white but the resized area being colored black.

Although, to avoid future confusion I think we should draw into the windows in the examples, even if it's just clearing them with the white pixel.
