### ISSUE TITLE
Bug Report: Window Fails on Wayland When `color-theme` setting is missing

### ISSUE THREAD

**Issue by lexi-the-cute** [rust-windowing/winit#2893]
When trying to create a window, I get the message `ERROR sctk_adwaita::config > XDG Settings Portal did not return response in time: timeout: 100ms, key: color-scheme`. As it turns out, I don't have the color-scheme setting on my system. I tested with the command `dbus-send --print-reply=literal --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read string:org.freedesktop.appearance string:color-scheme` and got the reply `Error org.freedesktop.portal.Error.NotFound: Requested setting not found`. I will have to mess with my own system so it'll have the setting, but there should be a way to bypass this and fallback to the theme the developer wants if auto is not available. For example, I would fallback to dark theme if this setting failed to be found.

The only ways I've been able to get the window to create is if I either launch the game with `WINIT_UNIX_BACKEND="x11"` such as with `WINIT_UNIX_BACKEND="x11" RUST_LOG="debug" cargo run` or if I log out of Wayland and switch over to X11 on my system.

**Comment by alexisart** [comment]
The relevant code is at https://github.com/PolyMeilex/sctk-adwaita/blob/4b61252dfe9d8961524d1176146b5a8b1406bf78/src/config.rs#L5-L24

**Comment by kchibisov** [comment]
I don't think we need winit specific env variable to control that given that winit has explicit theme API for `dark`/`light` theme on all platforms, so you could clearly pick it. application can do their own `light`/`dark` options explicitly.

The issue you get is due to broken portals setup on your system, so that's why you hit the delay in the first place, on systems without portals it'll work without a delay, though, such systems use server side decorations usually.

**Comment by A248** [comment]
I am running into the same issue. What is the "explicit theme API" I can use to avoid this call? There is noting wrong with the settings on my system, and every single other application functions correctly. 

A library shouldn't be issuing shell commands without a means to disable or configure them. Decisions by other developers might be relevant here: https://github.com/telegramdesktop/tdesktop/issues/17061

**Comment by kchibisov** [comment]
If you read the documentation on the theming, you have all the rights to disable this behavior, by simply picking a theme yourself when building a window. It's all documented.

**Comment by anelosima** [comment]
Same issue here. Picking a theme (either via with_theme or set_theme) doesn't resolve it; setting `WINIT_WAYLAND_CSD_THEME` doesn't resolve it; as in the OP, `WINIT_UNIX_BACKEND="x11"` works. If I check my dbus what is sent in response is `string "The name org.freedesktop.portal.Desktop was not provided by any .service files"` which is what I would expect; I do not have any XDG desktop portal. Apparently it would not be sufficient to merely install one; I would need to specifically have the GTK or GNOME backend, which are the only two which have that interface (according to a comment from 2021; maybe things have changed since then).

It is unclear to me why it represents a "broken portals setup" to simply not have one of the few packages which supply a particular interface.

**Comment by kchibisov** [comment]
@anelosima are you testing on the master or on 0.28.6? It doesn't have to do with running executables or anything and it's the default across other applications, like GTK. It just on linux the way to get the theme is via the dbus, so some clients just call to dbus method to pick a theme. Winit can avoid all of that if you use the `with_theme` API and set the theme explicitly to `dark` or `light`.

>It is unclear to me why it represents a "broken portals setup" to simply not have one of the few packages which supply a particular interface.

It basically means that your portals don't have all the env, etc available to them when they were activated via dbus, I hate this very much, but that's what folks decided to go with, because they need ways to communicate preferences to flatpaks somehow.

Usually you need something like `c --no-startup-id dbus-update-activation-environment --all` when you start your system in a bit non-standard way, and things like `XDG_CURRENT_DESKTOP` filled.

I'm not sure what is the best way forward with this, since if winit fails it means that basically any other GTK fails, but we should still **run**, there's no way winit or GTK won't start in such cases, if they do, then it's a completely different issue.

**Comment by kchibisov** [comment]
That's an API, but you'd need to pass `Some(Theme::Dark)` or `Some(Theme::Light)` and it won't work on non-betas, unfortunatelly. https://docs.rs/winit/0.29.1-beta/winit/window/struct.WindowBuilder.html#method.with_theme

**Comment by anelosima** [comment]
Ah! Updating to the latest beta solves it, sorry for the erroneous report; I had assumed that since this wasn't resolved it existed in the current beta, so I didn't bother updating. It also seems to solve it regardless of whether I set a theme through the API; no dbus message is being sent.

**Comment by kchibisov** [comment]
if your system doesn't use client side decorations, this API won't ever be touched.

**Comment by kchibisov** [comment]
The reason this issue is not resolved is that the initial bug says that the window fails, which I can't repro and I want to know whether it's still a thing.

**Comment by shanebenlolo** [comment]
also running into this issue on WSL2 on Windows 10, to reproduce:

```
mkdir learn_wgpu
cd learn_wgpu
cargo init
cargo add winit tracing tracing_subscriber wgpu
cargo run
```

main.rs:
```
use learn_wgpu::run;
fn main() {
    tracing_subscriber::fmt::init();
    run();
}
```

lib.rs
```
use winit::{
    event::*,
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

pub fn run() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| match event {
        Event::WindowEvent {
            ref event,
            window_id,
        } if window_id == window.id() => match event {
            WindowEvent::CloseRequested
            | WindowEvent::KeyboardInput {
                input:
                    KeyboardInput {
                        state: ElementState::Pressed,
                        virtual_keycode: Some(VirtualKeyCode::Escape),
                        ..
                    },
                ..
            } => *control_flow = ControlFlow::Exit,
            _ => {}
        },
        _ => {}
    });
}

```

This code is the result of following the first ~2 steps in the Learn WGPU blog post found here: https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#using-rust-s-new-resolver

**Comment by kchibisov** [comment]
>thread 'main' panicked at 'internal error: entered unreachable code', /home/shanebenlolo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/wayland/window/mod.rs:333:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[wayland-client error] A handler for wl_keyboard panicked.
Aborted

This has nothing to do with this issue. Install `libxkbcommon` to your environment. I'd assume you're on nix since you reached this.

**Comment by daaku** [comment]
This crashes with a panic. Wouldn't a fallback to either light or dark be better than crashing? I understand the developer can choose to provide their own setting, but as a user of an app built on top of `winit` I'm now unable to use pre-built binaries for the relevant application.

FWIW, a [sway](https://swaywm.org/) session with Wayland doesn't have such a setting by default.

**Comment by daaku** [comment]
> I'm not sure what is the best way forward with this, since if winit fails it means that basically any other GTK fails, but we should still **run**, there's no way winit or GTK won't start in such cases, if they do, then it's a completely different issue.

Without this setting GTK and Qt applications function correctly. The `winit` based application I'm trying to start - [inlyne](https://github.com/trimental/inlyne) - fails due to this missing setting.

**Comment by kchibisov** [comment]
I have no idea what are you talking about. Could you try with the recent winit example? On sway this won't ever touch the theme stuff with 0.29 which is available for at least half a year.

**Comment by daaku** [comment]
You're right, I pulled the source for the application on it was on `0.28.7`. Upgrading to `0.29.10` seems to include some API changes and I haven't attempted to fix those.
