### ISSUE TITLE
Massive stutters in firefox in 0.29.0-beta, 0.29.1-beta and master (games)

### ISSUE THREAD

**Issue by cybersoulK** [rust-windowing/winit#3105]
I spent the last several hours debugging this.
My game Normal behaviour in firefox is 120 fps stable
 
 I finally troubleshooted that 0.29.0-beta was causing issues in comparison with what i had previously: ed1425416813491380ce351816ab3f513c892058. 
Then i tested all of the versions including the current master 399edf57106aef4c36198c9513beb8ffb1aff349.

The master is by far the worst. 0.29.0-beta and 0.29.1-beta was 120 fps 90% of the time and then stutters down to 20 fps. The master stays at 25fps most of the time and occasionally freezes for 1 Second!!

Here is a video of the issue in current master: https://youtu.be/VCMHpYqanMg

I tested with the latest stable firefox.

**Comment by kchibisov** [comment]
Given that we have no idea what you're doing, I'd suggest to at least try to ask for `redraw_requested` on the window. There were also some different polling modes added for the `web`.

Maybe you just do `Poll` and draw, but we have no idea.

**Comment by cybersoulK** [comment]
i did window.redraw_requested at the end of RedrawRequested and inside AboutToWait.
is there something that i am missing?

**Comment by daxpedda** [comment]
> i tried window.redraw_requested at the end of RedrawRequested, and also tried it inside AboutToWait.
> is there something that i am missing?

It really doesn't matter where you call `redraw_requested()` from.

> I also don't touch ControlFlow at all, it says it's Poll by default

Using `Poll` in Firefox will currently just not work. But Winit can't do anything about that, it's just an issue with Firefox: `requestAnimationFrame()` will get throttled under pressure ([Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1427603)).

The reason it was working before is `Poll` was using rAF, which was incorrect. If you really need `Poll` in Firefox, consider using `PollStrategy::IdleCallback` from #3084, as @kchibisov already mentioned.

@kchibisov I would like to know how `Poll` is used in practice on other backends: because it just loops as fast as possible it will basically consume 100% CPU. For that reason I've never used `Poll` in practice except when testing stuff in Winit.

---

In any case, I will close this as it isn't really actionable from our side. @cybersoulK we are also guessing at your problem here because we don't have any information. If you can put together something reproducable it would be ideal.

**Comment by kchibisov** [comment]
>@kchibisov I would like to know how Poll is used in practice on other backends: because it just loops as fast as possible it will basically consume 100% CPU. For that reason I've never used Poll in practice except when testing stuff in Winit.

From what I can say, it's used with some blocking mechanism in the main loop, like vsync, but I'm not sure myself why you'd use poll. The only reason is to render as fast as possible, so you draw every time you wake up trying to blast frames per second.

I guess the use case for web in this issue is the same, they want to blast FPS.

**Comment by daxpedda** [comment]
> From what I can say, it's used with some blocking mechanism in the main loop, like vsync, but I'm not sure myself why you'd use poll. The only reason is to render as fast as possible, so you draw every time you wake up trying to blast frames per second.
> 
> I guess the use case for web in this issue is the same, they want to blast FPS.

Fun. Did we ever consider switching the default to `Wait`?

**Comment by kchibisov** [comment]
We could, will default of `Wait` work on the web?

**Comment by daxpedda** [comment]
Yes. Are you thinking of any specific reason why it wouldn't?

**Comment by cybersoulK** [comment]
It's firefox fault? But like i said https://github.com/rust-windowing/winit/commit/ed1425416813491380ce351816ab3f513c892058 works normal.

It's not only about the good fps, but also like you saw in the video, the alpha versions + master have massive stuttering, this is unusable. Can you guys switch like it was before, because it worked well

**Comment by kchibisov** [comment]
@cybersoulK have you read what we replied? Don't use `Poll`, use `Wait`, because `Poll` now follows other platforms and it's what web can't do.

**Comment by daxpedda** [comment]
> It's firefox fault? But like i said [ed14254](https://github.com/rust-windowing/winit/commit/ed1425416813491380ce351816ab3f513c892058) works normal.

From https://github.com/rust-windowing/winit/issues/3105#issuecomment-1727361207:
> The reason it was working before is `Poll` was using rAF, which was incorrect. If you really need `Poll` in Firefox, consider using `PollStrategy::IdleCallback` from #3084, as @kchibisov already mentioned.

> Can you guys switch like it was before, because it worked well

Using rAF for `Poll` is simply incorrect, so we can't switch back to that. In any case, if you are using `Window::request_redraw()` in every event loop cycle with `Wait`, you get the exact same behavior as before.

If this doesn't fulfill your requirements, you should point out exactly why so we can figure out how to proceed.

**Comment by cybersoulK** [comment]
Okay i am not really sure, i reverted all of my codes back and i can't try it right now. I also had people in gamedev community having issues with the newest versions. I will try it on the next non-alpha version of winit.

I have no idea of Poll vs Wait, but my game works on windows + mac + linux well, and a simple request_redraw loop works on firefox. Maybe make another controlFlow called Render instead of Poll or Wait? and just give it as default, it's confusing to me

**Comment by kchibisov** [comment]
But those a basics of control flow, winit also doesn't render anything. It's also documented which control flow does. `Poll` means spin the loop **as fast as it can**, the **Wait** means, wait for the actual event to arrive. Web can't spin as fast as it can on firefox, due to linked issue.

**Comment by cybersoulK** [comment]
Uhm, i had several major devs telling me to use Poll:

```
Poll if you're doing continuous rendering/animation on the same thread as your event handling (typical for games)
Wait[Until] if you're only updating on the same thread in response to events and don't want to pointlessly drain your user's battery (typicalish for business apps) 
```

```
as I understand it Wait + request_redraw is mainly meant to be used when you only want to redraw the window in reaction to events or something happening in your program
whereas for a game where stuff is changing every frame, you'd want to  Poll and let vsync (or some other accurate frame timing mechanism) decide when to draw
```

So it seems common sense between game devs to use the default ControlFLow which is Poll

**Comment by cybersoulK** [comment]
honestly i am not that smart, but if you are telling that game developers have to use Wait instead, that will break a lot of people codes, and they may not realize what's causing

**Comment by kchibisov** [comment]
I'm telling that **your particular case** needs `Wait` due to the reasons you outlined and how you actually draw:

1. You ask for event via the `Window::request_redraw`.
2. The `Wait`, will **always** wake you up, when it's time to draw, simply because you asked for an **event**.

This is also how it worked before, it was just implicit for you. But it means that before you wasn't able to draw faster than the `rAF` callback, now you theoretically can, if your browser can do so. But that's not what you want, you want `rAF` and `Wait` behavior, since that's how it basically was before.

`Poll` is only needed when you just draw and don't try to wake up the loop or don't care about throttling the frames. If you call `request_redraw` on every other platform, you don't even need `Poll`. `Poll` could also be needed if you try to spin up your own blocking solutions, but at this point, desktop gamedevs, can just use `pump_events` API for their loop and that's what Embark uses now (given that they even contributed it).

**Comment by daxpedda** [comment]
Winit is just a library, we try our best to make sensible APIs and document what they do. It is the responsibility of the library user to understand and know what they are doing. We are happy to give advice and explain, but we can't really decide for you or tell you what you need, you have to figure this out on your own.

While I was typing this, kchibisov already wrote what I was about to say. But I believe you should familiarize yourself with `ControlFlow` and learn about it's specifics instead of relying on others to tell you what to do.

**Comment by cybersoulK** [comment]
okay 👍 i will try Wait next version. So i just wanted to express the issue that i had to make sure you were aware, and you might get several other people with the same issue once they switch their codes, so maybe we can help them understand the API better once they reach out

**Comment by daxpedda** [comment]
I think I will go ahead and make a PR to switch to `Wait` by default and see what all the other maintainers think about that.
But generally speaking I think it might be good to overhaul the documentation around it and give better recommendations.

Thank you for your input @cybersoulK! If you have specific ideas on how to improve our documentation please don't hesitate to reach out.

**Comment by HoneyPony** [comment]
Hi, I'm coming across this issue while trying to figure out the proper way to use winit for a game. From what the documentation suggests:
```
    /// When the current loop iteration finishes, suspend the thread until either another event
    /// arrives or the given time is reached.
    ///
    /// Useful for implementing efficient timers. Applications which want to render at the
    /// display's native refresh rate should instead use [`Poll`] and the VSync functionality
    /// of a graphics API to reduce odds of missed frames.
    ///
    /// [`Poll`]: Self::Poll
```
It seems to me that `Poll` is the suggested behavior for applications that want to v-sync, which is generally what you want for desktop games, at least as a sensible default.

In the browser, I would expect that anything targetting v-sync would be using `requestAnimationFrame`, at least, based on my experience with `Emscripten` and so forth.

But it sounds like `Poll` does *not* give `requestAnimationFrame` behavior. That's fine, but it leaves me wondering: if I do want to default to targetting v-sync, and I want `requestAnimationFrame` in the browser, is the recommended usage to use Poll on desktop and Wait in the browser? Or is Wait also appropriate for desktop games?

This also might help explain some of the confusion here -- at least for people with my mindset, we read something that says "v-sync," and we think it must be doing something along the lines of `requestAnimationFrame` in the browser, because it vaguely related to v-sync (and there is no other mention of `requestAnimationFrame` in the documentation there).

In any case, switching my web build to `Wait` basically completely fixed its abysmal performance on Firefox, so thank you for the suggestion on that. :smile:

**Comment by kchibisov** [comment]
`request_redraw` and drawing on `RedrawRequested` should solve it for you on web, since it's where `requestAnimationFrame` is wired.

`Wait` would also make sense here.

**Comment by HoneyPony** [comment]
I should have mentioned -- I am repeatedly `request_redraw`'ing. I believe I have it set up (more or less) correctly -- I basically just `request_redraw` whenever I get the previous `RedrawRequested` event (right now, this is after I do the rendering + submitting the frame to the GPU -- I suppose it is unclear to me whether the ordering of these matters).

If I understood the exact semantics better, I might suggest some changes to the documentation for `ControlFlow` to suggest `Wait` for web applications. But, perhaps there is some scenario where `Poll` would actually make sense on web? It's unclear to me.

**Comment by kchibisov** [comment]
I'm not sure if `RedrawRequested` was wired to `requestAnimationFrame` in `0.29`, though, since you've mentioned master, testing it should give better idea.

IIRC `AboutToWait` might not happen on web in timely manner, so if you render in `AboutToWait` on `Web` it could be a _problem_.
