### ISSUE TITLE
Unaligned reference in safe functions

### ISSUE THREAD

**Issue by shinmao** [rust-windowing/winit#3125]
Hi, we found that the following functions could have unsound implementation
### Unsoundness in `platform_impl::platform::x11::Device::new`
https://github.com/rust-windowing/winit/blob/af247eac0f62fc4a1dfb025470f809d3413536d9/src/platform_impl/linux/x11/mod.rs#L1048-L1053
The safe function tried to transmute from `ffi::XIAnyClassInfo` to `ffi::XIScrollClassInfo`. After checking the definition,
```rs
#[repr(C)]
pub struct XIAnyClassInfo {
    pub _type: c_int,   // makes it aligned to 4 bytes
    pub sourceid: c_int,
}

#[repr(C)]
pub struct XIScrollClassInfo {
    pub _type: c_int,
    pub sourceid: c_int,
    pub number: c_int,
    pub scroll_type: c_int,
    pub increment: c_double,   // makes it aligned to 8 bytes
    pub flags: c_int,
}
```
the 4-bytes-aligned reference was converted to 8-bytes-aligned reference which was undefined behavior.

### Unsoundness in `platform_impl::platform::x11::Device::reset_scroll_position`
https://github.com/rust-windowing/winit/blob/af247eac0f62fc4a1dfb025470f809d3413536d9/src/platform_impl/linux/x11/mod.rs#L1083-L1086
`x11_dl::xinput2::XIValuatorClassInfo` is also aligned to 8 bytes; therefore, this function also created an unaligned reference

**Comment by madsmtm** [comment]
Thanks for spotting this, just curious, is this done using an automated script? It just seems to coincide with merging https://github.com/rust-windowing/winit/pull/3121?

In practice, I strongly suspect this will be fine, if X11 decides to hand out a `*mut XIAnyClassInfo` with that type, then it is going to be properly aligned.

More concerning is the usage of a reference to `XIAnyClassInfo` in the first place; creating that reference tells the Rust Abstract Machine that the size of the class info is only 8 bytes, which may be UB when we then try to access the later bytes through that reference (because the borrow does not have provenance of the larger `XIScrollClassInfo`).

What should be done instead is to keep `XIAnyClassInfo` as a raw pointer, read the type with `ptr::addr_of!`, and only then cast it into the correct type.

**Comment by shinmao** [comment]
> is this done using an automated script?

We are trying to test our parser and found something in the open-source.

> What should be done instead is to keep XIAnyClassInfo as a raw pointer, read the type with ptr::addr_of!, and only then cast it into the correct type.

Yes, you should change to raw pointer first because Rust's model doesn't allow unaligned reference to exist (even though it didn't happen, but that is what UB means). Also yes, `addr_of!` is the method to test the address. You can also cast to `usize` to acheive same goal. Another method is just to change it to `read_unaligned`.

**Comment by madsmtm** [comment]
> Rust's model doesn't allow unaligned reference to exist

Definitely true, but that's not the issue here, since the object is not created by Rust in the first place, but rather by X11 (which _does_ give it the correct alignment).

**Comment by shinmao** [comment]
@madsmtm Oh, I just read again about your comment:

> More concerning is the usage of a reference to XIAnyClassInfo in the first place; creating that reference tells the Rust Abstract Machine that the size of the class info is only 8 bytes

So it would be something like Rust only knows the 8-bytes `XIAnyClassInfo` contains `_type` and `sourceid`. However, the later code wants to get `number` which might be missed. Is that what you mean?

**Comment by madsmtm** [comment]
Yup, I've created [this gist](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=754cc935dbea37cbe0ebae8e21245eee) to show that Miri indeed flags this issue.

**Comment by shinmao** [comment]
Yes. I run the playground and see the retag issue with `transmute`. This issue has far more details than it seems :) Thanks for sharing such details!

**Comment by madsmtm** [comment]
> > is this done using an automated script?
>
> We are trying to test our parser and found something in the open-source.

My two cents on that: I think a _lot_ of maintainers appreciate you doing that, but I think they'd also have appreciated if you, in the issue description, explicitly state the degree to which the issue was created using automatic tools (because such tools are usually more fallible than humans).

> Thanks for sharing such details!

Np! I'm not really that invested in X11 myself, but I might open a PR to fix it if someone doesn't do it first.

**Comment by shinmao** [comment]
> explicitly state the degree to which the issue was created using automatic tools (because such tools are often more fallible than humans)

Yes. That's a good idea. I will include it in the statement in the future. Also, I manually check the report before I issue it; however, I miss the point that `XIAnyClassInfo` derived from X11. Thanks!

**Comment by kchibisov** [comment]
@madsmtm you can send a patch given that you sort of figured.
