### ISSUE TITLE
Feature request: Plateform feature flag for `NativeKeyCode` enum

### ISSUE THREAD

**Issue by nicopap** [rust-windowing/winit#3238]
### What problem does this solve?

The [`NativeKeyCode`](https://docs.rs/winit/0.29.3/winit/keyboard/enum.NativeKeyCode.html) enum has one variant per possible platform.

As far as I know, a given program can only run on a single platform at a time. It is statically impossible to have a `NativeKeyCode::Android` on an app compiled for Windows.

### Proposed solution

I think using an enum with one variant per platform is a good idea. It helps remind the programmer that the underlying key code value has different meaning depending on the platform. However, we don't care to handle `Xkb` keycodes on our macos/window/android app.

I suggest to use feature flags to only enable variants for the platforms we target.

Instead of this:
```rust
pub enum NativeKeyCode {
    Unidentified,
    Android(u32),
    MacOS(u16),
    Windows(u16),
    Xkb(u32),
}
```
We would have:
```rust
pub enum NativeKeyCode {
    Unidentified,
    #[cfg(android_plateform)]
    Android(u32),
    #[cfg(macos_plateform)]
    MacOS(u16),
    #[cfg(windows_plateform)]
    Windows(u16),
    #[cfg(any(x11_plateform, wayland_platform))]
    Xkb(u32),
}
```

This way, programmers using `NativeKeyCode` will still have to handle platform-specific behavior of keycodes, but only for the platform the app is compiled for.

Maybe I'm missing a key information here. The discussion on #753 is fairly lengthy and I only searched for keywords, without finding much discussion about this issue specifically.

**Comment by kchibisov** [comment]
IIRC the reasoning for that is that you can have cross-platform app where you can let the user bind and you also sync the confin, so you can have a separate binding for each platform when it comes to scancodes, otherwise you'll bind something user never wanted to bind, because scandoces do change from platform to platform. Generally, developers shouldn't even look at this enum, and this enum is used as a last resort of serialization/deserialization routine.

What should be used instead is `Key`, and in some rare cases `PhysicalKey`'s named variants.

There's also no need to add extra complexity be cfg-out specific backends, and X11, could be executed on Windows,macOS just about fine, the same comes for Wayland.

**Comment by kchibisov** [comment]
Also, given that dowstream gets the `PhysicalKey` or `Key` and unknown stuff is a saperate variant in each of them, you can simply map them to your `Unidentified` without even looking what it is and what the value it holds.

**Comment by nicopap** [comment]
Thanks for the clarification! Yeah, I don't think what I'm asking for makes sense, now that you explained it. Sorry for taking your time. Hopefully this can help other people.
