### ISSUE TITLE
Platform-specific getters on `WindowAttributes`

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/winit#3313]
Currently `WindowAttributes`s purpose is to expose the current state of `WindowBuilder`. But it doesn't support platform-specific fields.
It would be nice to move `PlatformSpecificWindowBuilderAttributes` into `WindowAttributes` so we can do that.

Alternatively, I'm not entirely sure why `WindowAttributes` exists in the first place if seemingly we could let users just get free (mutable) access to `WindowBuilder` fields and the ones we don't want them to get access to can have getters/setters.

What do you guys think?

**Comment by notgull** [comment]
Personally I think it's a good value add over having the structure's fields be exposed normally (semver issues). Although I support having the ability to access those platform specific fields as well. It would make it easier to make fuller wrappers around `winit` (e.g. `async-winit`)

**Comment by madsmtm** [comment]
I dislike `WindowAttributes`, and think it should've been private to begin with; it allows us to more easily change implementation details, while still exposing a stable API behind the setter methods. But then again, Winit is perma-unstable, so eh, maybe it doesn't really matter.

Back when I tried to remove it in https://github.com/rust-windowing/winit/pull/2134, it was met by resistance because there were no getters, and that broke people relying on being able to access the current builder values.

**Comment by daxpedda** [comment]
See #2613 for the discussion on why it was reverted.

Generally speaking I really do dislike `WindowAttributes`, but I've learned over time that having builders without getters will always spawn requests, so I tend to consider them "good API design".

Personally I think we either remove `WindowAttributes` and introduce a *lot* of getters, or leave `WindowAttributes` in place.

In the mean time I will go ahead and move `PlatformSpecificWindowBuilderAttributes` into `WindowAttributes`.
