### ISSUE TITLE
Hashing `WindowId` to associate per-window data should not be necessary

### ISSUE THREAD

**Issue by david7a68** [rust-windowing/winit#3464]
With the current event loop 3.0 changes, would it be possible to bind per-window data directly to windows such that binding per-window data does not require a `HashHap<WindowId, Data>` in multi-window contexts? Using the new `Application` trait, it should be possible for a pair of `window_create(...)->Data` and `window_destroy(Data)` such that items bound to window lifetime can be handled gracefully.

This is not directly related to platform abstraction, but it makes managing per-window state much simpler.

It should be sufficient to default to `()` automatically when no per-window data is desired.

**Comment by kchibisov** [comment]
Well, you don't have to hash, you just have to store your windows somehow. `HashMap` is more convenient, but what will be the way otherwise? For example, you get an event for window with id `3` and you have 20 windows, you have to somehow get the `Window` and do requests, so you store all your windows already in some data structure, thus what you suggest seems like it'll just complicate the code for no actual reason, since now you have some container holding all your `Window` and you have some way to get data associated with window, where such data should also be opaque to winit, but be `Send`/`Sync` and have some sort of sync access around it.

If you're worried about lifetime, well, you can't force everyone to put all their state into winit, so it won't really make it any safer, it's also a bit weird to access your data via winit in MT context, given that you really don't need your window most of the time to do anything, like you don't need your entire window to draw and your window and render surface may reside on different threads.
