### ISSUE TITLE
Mutex in X11 backend locked twice without unlock

### ISSUE THREAD

**Issue by bvssvni** [rust-windowing/winit#347]
See https://github.com/PistonDevelopers/piston_window/issues/215#issuecomment-343635266

> @bvssvni looks to be happening in the winit's X11 window destructor. PoisonError is for mutex being locked twice without unlocking. I suggest filing an issue to winit.

cc @kvark 

For backtrace, see https://github.com/PistonDevelopers/piston_window/issues/215#issue-267496086

**Comment by Ralith** [comment]
The mutex may be unnecessary as of #191.

**Comment by francesca64** [comment]
The mutex problems don't happen anymore, though now it segfaults in `XCloseIM`, which is quite unusual (since the input method shouldn't be closing). Fixing that is [trivial](https://github.com/francesca64/winit/commit/e77a6c245a73db8156d12c893ab42cad71196751), but while that allows multi-window Piston applications to run, they won't have working IME

IME works fine in single-window Piston apps, and fine in non-Piston multi-window apps (even multi-threaded ones). Someone more versed in Piston's internals would have to help out on investigating. This is a very unusual issue, and I imagine it comes down to the unsoundness of Xlib in some way or another (the XIM client is especially bad). If Piston's multi-window code is using multi-threading somewhere, that's a likely suspect.

**Comment by kchibisov** [comment]
I don't think this is relevant anymore.
