### ISSUE TITLE
Keep receiving keyboard events even if the window is `Focused(false)`

### ISSUE THREAD

**Issue by pwbh** [rust-windowing/winit#3519]
I am working on an app and it uses `winit` to inject a window into a canvas. I am wondering if its possible somehow to keep receiving events even if the canvas is not focused? I do see that the cursor event are received even though canvas is not focused. Sot I wonder if its possible to make it work the same for keyboard events?

Thanks.

**Comment by madsmtm** [comment]
Since you said "canvas", I assume you're building your application for the web.

From what I know, it is impossible to keep keyboard focus if the user switches away from the browser tab; that would be a major security hole.

But if you're fine with that limitation and just want to handle the case of the user clicking somewhere outside of your canvas but on a webpage that you still control, I think you could do this by adding a keyboard event listener to the root element?

**Comment by pwbh** [comment]
This was my initial thought, wanted to ask here before writing my own logic for this, was thinking maybe winit had something "batteries included". Thanks.

**Comment by daxpedda** [comment]
> I do see that the cursor event are received even though canvas is not focused. Sot I wonder if its possible to make it work the same for keyboard events?

The only reason why this isn't implemented is because it doesn't align with the other backends and the current API. So its definitely possible if we address this in a cross-platform manner.

**Comment by pwbh** [comment]
@daxpedda that could be a great improvement. Shall I keep this issue open?
I could even help implement this if someone is willing to guide me to the right place in the code :)

**Comment by daxpedda** [comment]
> @daxpedda that could be a great improvement. Shall I keep this issue open?

I think this needs a dedicated issue.
Basically the ask here is to expand `DeviceEvent::Key` to have more information or maybe match up with `KeyEvent` and see what the lowest common denominator between backends is.
