### ISSUE TITLE
Scaling broke on Wayland (between version `0.28.7` and `0.29.15`): the window is twice the size it should be when the scaling factor is `2`

### ISSUE THREAD

**Issue by SimonBrandner** [rust-windowing/winit#3868]
When the scaling factor is `2` and I set the window size using `ViewportBuilder::with_inner_size()` in EGUI, the window ends up twice the size it should be (4 times the original amount of pixels). Things like images inside the window get scaled correctly 

As far as I can tell the bug was introduced between these versions: https://github.com/rust-windowing/winit/compare/v0.29.15...v0.28.7

![image](https://github.com/user-attachments/assets/1e143095-9b37-4ef5-97b0-365be4a024bf)

(the image and window should have the same size here)

This could also be an [EGUI bug](https://github.com/emilk/egui/issues/4960), I don't know

**Comment by kchibisov** [comment]
if the window is not blurry it's not our bug, ensure that you set the size with the logical pixels correctly.

Keep in mind that whatever winit does with sizes, it won't change anything in your code on Walyand, since size on Wayland effectively means nothing in winit and you have full control when it comes to buffer sizes in your application.
