### ISSUE TITLE
Add Window::get_fullscreen() -> bool

### ISSUE THREAD

**Issue by rukai** [rust-windowing/winit#579]
`set_fullscreen` takes an `Option<WindowId>`.
However we dont need to make `get_fullscreen()` return an `Option<WindowId>` because we can use `get_current_monitor() -> WindowId` instead.

The window manager (at least on X11) can set the fullscreen state so just remembering the state in winit will not be enough.

**Comment by francesca64** [comment]
The way I'd want to address this is similar to #208, since:

- Maximization events are necessary and it would make sense for the fullscreen API to follow the same pattern.
- There's also a fullscreen button on macOS.
- I tend to favor events over getters, since people presumably usually only want to know about changes, and only as often as they happen.

So I'd go with `WindowEvent::Fullscreen(Option<MonitorId>)`. However, I'm not opposed to having the getter as well, though I think it really should return `Option<MonitorId>`, for consistency with `set_fullscreen`. That also makes it easier to do dumb stuff with combinators.

**Comment by rukai** [comment]
Thanks, that all makes sense.

**Comment by francesca64** [comment]
Are there any WMs you recommend for testing this?

**Comment by rukai** [comment]
Not sure if your asking me directly? I only use i3.
