### ISSUE TITLE
Duplicate key events on macOS

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#734]
It has been reported to Alacritty that in certain circumstances the `Paste` key is sent multiple times to the winit application.

The relevant bug report in Alacritty can be found here:
https://github.com/jwilm/alacritty/issues/1842

Based on the troubleshooting there, it looks like the key event is actually sent twice, however user-related problems probably can't completely be excluded since there has been noone able to reproduce this issue.

My initial thought was that it might be related to key repeat rate, but that seems to be default.

**Comment by rrichardson** [comment]
FWIW I can reproduce this issue.  As a few others who use the Dvorak keyboard (or other alternate) layouts

**Comment by rrichardson** [comment]
Interestingly, it is **only** for `Command + Period`   I can't explain why. 

If I remap it to `Control + Period` it works fine.  If I remap it to `Command + Comma` or any other value, it is fine. 

If I remap it to `Control + .` . it doesn't send twice.

**Comment by hobogenized** [comment]
I've found something that might be related. After changing the alacritty config to use "Cmd + ." to do paste and changing my keyboard layout to Dvorak, I found that doing "Cmd + ." according to the Dvorak layout does nothing, but doing "Cmd + v" according to the Dvorak layout will paste twice. "v" on the Dvorak keyboard layout corresponds to "." on the QWERTY keyboard, so there's a chance that keyboard inputs are not processed cleanly according to the current keyboard layout.

**Comment by nolanderc** [comment]
I've been digging into the source code for the macOS `EventsLoop` implementation and found something interesting:

https://github.com/tomaka/winit/blob/8e733543cdc1c8b0ab4172f3fd2d9ef98b23dce1/src/platform/macos/events_loop.rs#L318-L338

It appears as if there once was a bug in AppKit where key-up events weren't being sent to the right window while the `Command` key was held. To my understanding, however, `Command + Period` had the opposite behaviour: ignoring key-down events. 

The code quoted above attempts to address this bug by inserting the correct key-down event for `Command + Period` into the stream. But at some point it seems this issue was addressed and events are now being sent twice: once from AppKit and once from the patch.

After some testing: removing the `appkit::NSKeyDown` branch seems to eliminate all duplicate events.

**Comment by kchibisov** [comment]
long resolved.
