### ISSUE TITLE
Virtual Keycode is incorrect on macOS non-qwerty layouts

### ISSUE THREAD

**Issue by Toqozz** [rust-windowing/winit#752]
The `virtual_keycode` field seems to be incorrect when using a non-qwerty layout.  It seems to always return values corresponding to the qwerty (or perhaps physical?) layout.

I'm running the following program:
```
extern crate winit;

fn main() {
    let mut events_loop = winit::EventsLoop::new();
    let window = winit::Window::new(&events_loop).unwrap();

    events_loop.run_forever(|event| {
        println!("{:?}", event);
        match event {
            winit::Event::WindowEvent {
                event: winit::WindowEvent::CloseRequested, ..
            } => winit::ControlFlow::Break,
            _ => winit::ControlFlow::Continue,
        }
    });
}
```

Pressing a dvorak `P` here (qwerty 'R')  results in the following lines:
```
WindowEvent { window_id: WindowId(Id(140217433672064)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 15, state: Pressed, virtual_keycode: Some(R), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }

WindowEvent { window_id: WindowId(Id(140217433672064)), event: ReceivedCharacter('p') }
```

As you can see, we receive `virtual_keycode: Some(R)`.  Also note that right after the window receives the `P` character.  (Shouldn't these always be the same?)

The issue doesn't seem to occur on Linux/X11.

```
winit version: 0.18
MacBook Pro (2017)
macOS version: 10.14 (Mojave)
```

**Comment by francesca64** [comment]
Thanks for reporting this!

We're currently using `NSEvent keyCode` to [generate `VirtualKeyCode`](https://github.com/tomaka/winit/blob/45a428141329377a1669698e4ca6561834c0dbcc/src/platform/macos/events_loop.rs#L547): https://github.com/tomaka/winit/blob/139686ddce870614f12eb3a0ed33a9adfee1e47a/src/platform/macos/view.rs#L415

This is wrong, since that's really just a scancode: https://stackoverflow.com/a/18413469/5435443

We likely inherited this oversight from GLFW, since it's done the same way there (and in SDL). It doesn't look like AppKit has a concept of layout-aware virtual key codes. WebKit has a good explanation and solution here: [`windowsKeyCodeForKeyEvent`](https://github.com/WebKit/webkit/blob/89c5f8dd6b6108bfd066b281376c08ac900a7aa7/Source/WebCore/platform/mac/PlatformEventFactoryMac.mm#L566), [`windowsKeyCodeForCharCode`](https://github.com/WebKit/webkit/blob/82bae82cf0f329dbe21059ef0986c4e92fea4ba6/Source/WebCore/platform/cocoa/KeyEventCocoa.mm#L626)

If you're interested in contributing, this would likely be an easy PR.

**Comment by Toqozz** [comment]
I will definitely have a look, thank you!

**Comment by francesca64** [comment]
@chrisduerr are you aware of any Alacritty bugs that look like they're caused by this? (or any people who might want to test #755?)

**Comment by chrisduerr** [comment]
The issue that comes to mind is https://github.com/jwilm/alacritty/issues/458. I've linked the PR there for anyone interested in testing.
