### ISSUE TITLE
Allow ignoring Xft.dpi

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#836]
Winit has recently gotten the ability to set a fixed DPI on all displays in X by using the Xft.dpi file, however this makes it impossible to have dynamic scaling in winit while manually setting the DPI for other applications, since as soon as the file is found all dynamic scaling is disabled.

This has been reported to Alacritty in https://github.com/jwilm/alacritty/issues/2271.

I see three ways to solve this issue:
 - Keeping things the way they are right now, user just needs to know and work around this
 - Introduce an env variable to force dynamic scaling and ignore Xft.dpi
 - Introduce an env variable which applies Xft.dpi on top of dynamic scaling

I'm unsure which of these would be the best option, though the first seems unfortunate. I think that the second would be my personal favourite but maybe we can even make this a Rust function and skip pointless environment variables?

**Comment by lespea** [comment]
What if get_output_info took another parameter to force calculation of the dpi by using the width/height of the screen?

**Comment by chrisduerr** [comment]
With the release of Alacritty 0.4.0, this has been brought up again and I think it's a very good point. I personally like winit's scaling too, so I would be annoyed if I had a monitor that required me to use Xft.dpi for other applications without being able to ignore it for Alacritty.

Fundamentally this should be trivial to fix, I can send a PR for this myself so that's no problem. The only question is about *how*.

I'm not sure what GTK's `gdk_monitor_get_scale_factor` does, but based on the behavior of GTK, I'd expect it to not be what we would want. Also having per-monitor scaling is not the issue, that's already working today. The issue is with being able to ignore `Xft.dpi` and even when using `gdk_monitor_get_scale_factor` we'd run either into the scenario where `Xft.dpi` is always ignored (which we do not want), or `Xft.dpi` is never ignored, which is described in this issue.

So I think fundamentally keeping this issue open to look into GDK's monitor DPI function will likely not bear any fruits and just delay an actual solution even further.

I understand that environment variables aren't great, however even the `WINIT_HPDPI_FACTOR` variable is already used by many because it's just something people need. So I think perfect is the enemy of good in this way, especially because perfect does not exist with X11 DPI.

I'd propose either making the decision to expose it in the API, or to offer an environment variable and then just go with it. I'm fine with either, however I don't think waiting will improve anything with X11.

**Comment by kchibisov** [comment]
I would like to add some additional notes to what @chrisduerr already mentioned.

First of all we have a `WINIT_HIDPI_FACTOR` variable which is X11 **only** thing. That being said why should we add one more variable if we can just improve the existing one. Let's say `WINIT_HIDPI_FACTOR=0` would mean use auto dpi guessing etc, since 0 doesn't make sense and no one should use it right now for anything. I think it'll be a compromise and a natural addition to the current variable, which could improve debugging of `winit`'s dpi on X11 and some users workflow.

I also don't like such generic name for X11 env variable, however we should keep it for backward compatibility, I guess. `WINIT_X11_HIDPI_FACTOR` makes much more sense tbh, but it's a story of the past, isn't it?

As for a `GTK`(GDK) thing, I'm completely against using GTK API in any way in winit, since it's pretty heavy dependency for a thing that doesn't require it in a first place and will break on systems that could be without `GTK`.

**Comment by chrisduerr** [comment]
> I also don't like such generic name for X11 env variable, however we should keep it for backward compatibility, I guess. WINIT_X11_HIDPI_FACTOR makes much more sense tbh, but it's a story of the past, isn't it?

I don't think renaming it would benefit anyone.

**Comment by kchibisov** [comment]
>I don't think renaming it would benefit anyone.

Agree, it's just me not liking that X11 only option is called *so* generic.
