### ISSUE TITLE
Transparent and borderless window on Windows 10

### ISSUE THREAD

**Issue by qthree** [rust-windowing/winit#851]
Both `WindowBuilder::with_transparency(true)` and `WindowBuilder::with_decorations(false)` are working well by themselves on Windows 10, but their interaction leads to "invisible" unresponsive window (it "screenshots" image that was under window before it appeared).

Culprit is `WS_EX_LAYERED` flag [here](https://github.com/rust-windowing/winit/blob/master/src/platform/windows/window_state.rs#L201). I've removed it and window appeared like it should. But i'm not sure if it's proper fix for all versions of Windows.

**Comment by Osspial** [comment]
Could you go ahead and make a PR for this fix? We can get someone to test it on Windows 7 more easily once that exists, and merge it if it works everywhere.

**Comment by baysmith** [comment]
Has anyone else seen that transparent and bordered windows on Windows 10 are not working properly?

I'm seeing what I think is the trail effect described with the fix by SetLayeredWindowAttributes on LWA_ALPHA. However, if I restore setting WS_EX_LAYERED, the problem seems to be fixed, but that must be set only with decorations since it causes borderless windows to not render.

**Comment by Osspial** [comment]
@baysmith Thanks for looking into this! Fixing this should just be a matter of setting that flag for bordered windows and unsetting it for borderless windows.

Since you did the investigation into this issue, could you make the PR implementing the fix? If you're not interested in doing that I can go ahead and make the PR though.

**Comment by baysmith** [comment]
I'd be happy to make a PR.
