### ISSUE TITLE
Windows nested WNDPROC multiple borrow_mut panic.

### ISSUE THREAD

**Issue by crlf0710** [rust-windowing/winit#864]
**I'm using eventloop-2.0 branch. Not sure if this applies to master branch. I assume it does.**

There're many cases that WndProc will be called, and sometimes even in a nested style. Here's a simple repro:
in examples/timer.rs, at the position of println!("\nTimer\n"); add 
````
use winit::dpi::LogicalSize; 
_window.set_inner_size(LogicalSize::new(300.0, 300.0));
````
the program will panic saying 
````thread 'main' panicked at 'already borrowed: BorrowMutError', ````
the outer borrow is:
````platform_impl/windows/event_loop.rs:173: runner!().new_events()````
the inner borrow is in ```WM_PAINT``` handling within ```public_window_callback```: 
````let mut runner = subclass_input.event_loop_runner.runner.borrow_mut();````

In this specific case, i can workaround it by removing the `UpdateWindow` call within `set_inner_size_physical`. But i'm sure there's more ways to get this panic triggered.

@Osspial

**Comment by Osspial** [comment]
Hi, and thanks for the report!

You're right that removing `UpdateWindow` isn't the most ideal solution, since it doesn't solve the underlying problem that various winapi calls can dispatch `WM_PAINT` events outside of the normal event loop control flow. Fortunately, looking at the code, it doesn't look like the `borrow_mut()` call is actually necessary! I'm pretty sure I initially added it to properly handle [this case in the API](https://github.com/rust-windowing/winit/blob/eventloop-2.0/src/window.rs#L366-L370), but that handling has been moved to a separate event's handler so we can replace all that code with a different set of event dispatch code that handles that case.

I've made a PR to fix this here: #866.

Also, pretty much all of the event loop code was rewritten for the eventloop-2.0 branch, so this problem shouldn't show up on master.
