### ISSUE TITLE
Provide a way to return from the event loop

### ISSUE THREAD

**Issue by spennydl** [rust-windowing/winit#900]
Currently we have #797 and #845 working on bringing in webassembly support.  Unfortunately, in the browser we have to return from function calls.  These backends both have to rely on throwing exceptions as control flow in order to break out of the loop.

Is there a way winit could provide some mechanisms for loops that work this way?  I noticed some of the other backends implement a `run_return` function that is usually called by `run`; perhaps winit could standardize on this?

**Comment by est31** [comment]
See prior discussions on the topic: https://github.com/rust-windowing/winit/issues/459#issuecomment-409183722

https://github.com/rust-windowing/winit/issues/459#issuecomment-410351174 explicitly says that throwing exceptions is the intended design.

**Comment by Osspial** [comment]
Throwing exceptions is indeed the intended design. It's not particularly pretty, but it's the only API I'm aware of that behaves mostly identically on all platforms.

**Comment by blm768** [comment]
Seems like a reasonable approach would be to offer both methods. Since WebAssembly initialization tends to require platform-specific tweaks anyway (i.e. for resource loading, since standard filesystem APIs aren't available), most programs targeting a `wasm` backend would probably go through the specialized `run_return` function anyway. Having a bit of "shim" code to adapt this into "`run`+throw" would (hopefully) take care of the programs that don't.

There *is* one additional concern that was [mentioned briefly](https://github.com/rust-windowing/winit/issues/459#issuecomment-471338992) but may require further analysis: at least according to the `wasm-bindgen` docs, WebAssembly has no support for stack unwinding, which means that nothing that was constructed between the start of the entry point function and the exception that breaks out of `run` will be `Drop`ped properly. I've had this issue bite me multiple times when working on my own project; with the kinds of borrowing patterns that are common in WebAssembly projects, almost anything that panics tends to leave "borrowed" `RefCell`s that become permanently locked and unusable. This can also affect program semantics in other, more subtle ways, which users may not have accounted for when trying to port their code to work in a `wasm` environment.

**Comment by Osspial** [comment]
If we're exposing `run_return` on desktop platforms, I see no reason not to expose an equivalent method for WASM platforms. It should be named differently through, to prevent confusion.

**Comment by daxpedda** [comment]
This is covered by [`EventLoop::spawn()`](https://docs.rs/winit/0.28.6/wasm32-unknown-unknown/winit/event_loop/struct.EventLoop.html#method.spawn).

Fixed by https://github.com/rust-windowing/winit/pull/2208.
