### ISSUE TITLE
Add documentation for implementing a game loop

### ISSUE THREAD

**Issue by LaylConway** [rust-windowing/winit#956]
Currently the documentation shows a method of looping common for UI applications, but not game loops. It's in fact fairly non-trivial to figure out how you would set up a game loop with or without a frame timer right now.

Since games are a major use case for winit, it would be a good idea to have this be very front and center, since it is in fact possible and not that hard to do, but just non-trivial for people used to other APIs.

For reference for other people running across this issue:
- Update and render your game on `Event::EventsCleared`.
- Set the control flow to `ControlFlow::Poll` (Poll will keep trying to poll for events and keep passing EventsCleared, Wait will only pass EventsCleared after it has found and processed at least one event)

**Comment by tuzz** [comment]
For anyone stumbling on this via a google search, I have a crate [here](https://github.com/tuzz/game-loop) that implements a frame-rate independent game loop based on the ['Fix your timestep!'](https://gafferongames.com/post/fix_your_timestep/) article.

I just added winit support to the crate so that might be useful if you want to run a game loop inside a winit window. Of course, you can roll your own easily enough but it might save you some busywork.
