### ISSUE TITLE
Add pointer grab for Wayland

### ISSUE THREAD

**Issue by Cherser-s** [rust-windowing/winit#962]
pointer_constraints_v1 extension has been around for almost a year. It is already supported in wlroots.

**Comment by vberger** [comment]
This will need to go through https://github.com/Smithay/client-toolkit/issues/72

**Comment by Cherser-s** [comment]
Does this functionality need to belong there? Seat manager isn't implemented in client-toolkit for example.

**Comment by vberger** [comment]
SCTK goal is to provide general abstractions facilitating the use of the various wayland protocol extensions. The seat manage is not provided by it because it contains mostly winit-specific code, but it uses SCTK for handling the translation of keyboard events for example.

In the same approach, I expect the support of pointer-constraints and relative-pointer will caontain both winit-specific code and code that may be re-used in other apps. The latter part could live in SCTK to improve re-usability and simplify maintenance.

**Comment by Cherser-s** [comment]
Ok, but there is probably no need to implement relative pointer extension in SCTK, except for modifying ```Environment``` struct.

Also, adding relative pointer will require DeviceEvent queue. Now only WindowEvent queue is implemented.

**Comment by vberger** [comment]
Well, I hadn't really started to look into these protocols so this was kind of a generic response. If you already have a working implementation, this will be easier to discuss with a PR though.

**Comment by Cherser-s** [comment]
Ok, I wrote implementation yesterday evening though.
