### ISSUE TITLE
EventLoop 2.0 misreporting DPI Factor at startup on X11

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#998]
While looking at some remaining bugs in the EventLoop 2 version of Alacritty, I've noticed that the DPI Factor is always `1` at startup, regardless of which monitor the window is spawned on.

If the monitor is moved between monitors, the DPI is always updated correctly. So starting on a monitor with a 2.0 DPI and moving it to a different monitor and back will 'fix' the incorrectly reported DPI.

**Comment by murarth** [comment]
How is the initial DPI factor value reported to the application? `Window::hidpi_factor`?

**Comment by chrisduerr** [comment]
Yes, it's just a call to the window's hpdpi_factor method. I've had it before `set_visibe(true)` originally, but even after that it does not work properly.

**Comment by kchibisov** [comment]
Just to make it clear. This issue is only presented in a multi monitor setup. I'm also testing the same `alacritty` branch as @chrisduerr does, but I've only had one monititor and the startup DPI seems correct to me (it's `2.3333333333333335`, which is correct for my system).

**Comment by kchibisov** [comment]
It seems like the some initial calls to `hidpi_factor()` queries a wrong monitor and then changes to appropriate one, however there is no `HiDpiFactorChanged` event when `last_monitor` is changing, so `alacritty`, which is absolutely relying on this event now, fails to resize itself on a next resize event (our `master` was also recheking `hidpi_factor` on resize, so it was kind of working around this behavior).

Log that proves, what I've said here. There were a `println!("DPR CHANGED!!!")` in `HiDpiFactorChanged` handler in `alacritty`, which you can't see here, because of the above reason.

DPI FACTOR CALL is `println!("DPI FACTOR CALL {:?}", monitor.name);` in `hidpi_factor()` [function](https://github.com/rust-windowing/winit/blob/57a53bda74fa9a46e7e282d0f857d02048e64353/src/platform_impl/linux/x11/window.rs#L1215).

As you can see the issue was presented with `winit` `v0.19.1` too.
```
evlp2:
Created log file at "/tmp/Alacritty-38879.log"
[2019-09-16 01:01] [INFO] Welcome to Alacritty
[2019-09-16 01:01] [INFO] Configuration loaded from "/home/kchibisov/.config/alacritty/alacritty.yml"
DPI FACTOR CALL "eDP-1"
[2019-09-16 01:01] [INFO] Device pixel ratio: 2.3333333333333335
DPI FACTOR CALL "eDP-1"
[2019-09-16 01:01] [INFO] Initializing glyph cache...
[2019-09-16 01:01] [INFO] ... finished initializing glyph cache in 0.035028809s
[2019-09-16 01:01] [INFO] Cell Size: 13 x 26
[2019-09-16 01:01] [INFO] Padding: 0 x 0
[2019-09-16 01:01] [INFO] Width: 1333, Height: 1000
[2019-09-16 01:01] [INFO] PTY Dimensions: Line(38) x Column(102)
[2019-09-16 01:01] [INFO] Initialisation complete
DPI FACTOR CALL "eDP-1"
DPI FACTOR CALL "eDP-1"
DPI FACTOR CALL "DP-2"
[2019-09-16 01:01] [INFO] Width: 1906, Height: 2106
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
[2019-09-16 01:01] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-38879.log"

master:
Created log file at "/tmp/Alacritty-42742.log"
[2019-09-16 01:03] [INFO] Welcome to Alacritty
[2019-09-16 01:03] [INFO] Configuration loaded from "/home/kchibisov/.config/alacritty/alacritty.yml"
DPI FACTOR CALL "eDP-1"
[2019-09-16 01:03] [INFO] Device pixel ratio: 2.3333333333333335
DPI FACTOR CALL "eDP-1"
[2019-09-16 01:03] [INFO] Initializing glyph cache...
[2019-09-16 01:03] [INFO] ... finished initializing glyph cache in 0.035323723s
[2019-09-16 01:03] [INFO] Width: 1707, Height: 1280
[2019-09-16 01:03] [INFO] Cell Size: 13 x 26
[2019-09-16 01:03] [INFO] Padding: 0 x 0
[2019-09-16 01:03] [INFO] PTY Dimensions: Line(49) x Column(131)
[2019-09-16 01:03] [INFO] Initialisation complete
DPI FACTOR CALL "eDP-1"
DPI FACTOR CALL "eDP-1"
DPI FACTOR CALL "eDP-1"
DPI FACTOR CALL "eDP-1"
DPI FACTOR CALL "eDP-1"
DPI FACTOR CALL "eDP-1"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
[2019-09-16 01:03] [INFO] Font size changed to Size(14) with DPR of 1.6666666666666667
[2019-09-16 01:03] [INFO] Width: 1906, Height: 2106
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
DPI FACTOR CALL "DP-2"
[2019-09-16 01:03] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-42742.log"
```

**Comment by kchibisov** [comment]
I'm not sure if detecting the correct monitor on startup is possible on X11, but sending `HiDpiFactorChanged` on `last_monitor` (from `Some` to `Some`) change will make sense in my opinion. What do you think @ZeGentzy @murarth ?

**Comment by murarth** [comment]
@kchibisov I agree that sending a `HiDpiFactorChanged` event to ensure that the application has the correct DPI seems like a reasonable solution to me. I'll get started on a PR for this.

**Comment by nixpulvis** [comment]
@murarth anything to share? I'd be curious to start trying this out, or building it. I'm currently unable to use Alacritty's `master` branch until we fix either this issue or #1246.

**Comment by murarth** [comment]
@nixpulvis I don't know what happened, but I completely forgot about this issue. So sorry. I'm working on it right now.

**Comment by murarth** [comment]
So, the issue appears to be this:

When an X11 window is created, winit guesses its DPI factor based on the current position of the mouse pointer (as this is where a WM will typically place a new window) and stores this guessed value in `SharedState` as `guessed_dpi`. When a `ConfigureNotify` event arrives, winit can know for certain what the new window's DPI factor is. If it guessed correctly, no DPI adjustment needs to be made. (This behavior was introduced in #583 to avoid unnecessary resizing immediately after window creation, as winit would previously assume a DPI factor of `1.0`.)

This bug occurs because, while winit makes a guess about which monitor it expects to contain the new window, it does not use this guess to fill in the window's `current_monitor()` value. This gives applications inconsistent information.

I think the best solution to this issue is to use the guessed monitor as a window's current monitor on window creation. Yes, the guessed value may be incorrect on some WMs, but that was also true before and at least this way, we give consistent information that will be corrected if necessary. I'll have a PR implementing this solution shortly.

**Comment by kchibisov** [comment]
>I think the best solution to this issue is to use the guessed monitor as a window's current monitor on window creation. Yes, the guessed value may be incorrect on some WMs, but that was also true before and at least this way, we give consistent information that will be corrected if necessary. I'll have a PR implementing this solution shortly.

This wont resolve the issue though, if your mouse in on monitor `1` and you open an application on monitor `2`, then you'll get a wrong dpi, since initially you're querying primary display (assume `1`) and your mouse is also on monitor `1`.

I think to resolve this issue properly you either need to query a right monitor or whenever you update dpi send a `HiDpiFactorChanged` event. Setting a guessed dpi will just workaround some cases, but it still be annoying if you don't use your mouse regularly (assume i3).

**Comment by chrisduerr** [comment]
The biggest problem is with initial events really when you're not sure what DPI a resize event is coming in at. Like the new `RedrawRequested` that is sent right now. If you query when that event comes in, the DPI is still incorrect.

Additionally, we can't just query `hidpi_factor` with every resize event, both because the DPI at the point we process it might be different from the DPI of the event itself and because `hidpi_factor` is expensive in our experience.

As a user I wouldn't particularly care what the initial DPI is, as long as I get a HiDPIFactorChanged event as soon as it changes. So I'd be fine with always initializing at 1 on X11 for example, we just need to get our DPI updated by a winit event properly before a resize comes in and on i3 for example a resize will come in right at startup.

I'd also like to ping @Osspial, since I think he might know a thing or two about the DPI rework. I feel like that might just solve everything anyways, but I don't know anything about its current state. However as an enduser getting a fix quicker rather than later is obviously preferred, but sometimes doing things right takes some time.

**Comment by murarth** [comment]
@kchibisov Yes, the guessed monitor may be incorrect, but when the `ConfigureNotify` event arrives, if it places the window on a monitor other than the one winit guessed, a `HiDpiFactorChanged` event will occur and the window will have the correct `current_monitor()` at that time.

> whenever you update dpi send a `HiDpiFactorChanged` event.

This is already the current behavior. A `HiDpiFactorChanged` event wasn't being issued only in the case of a new window because, internally, winit had already correctly guessed the DPI factor and didn't consider a change to have occurred. The change I've proposed will share the guessed monitor with the application, resolving the inconsistent information provided to the application.

It's still possible that winit will incorrectly guess the starting monitor, but that will be corrected when winit receives this information and the existing behavior is to make the application aware of this. It's unavoidable that winit won't know the true position of the window until the WM sets its position. All we can do is resolve the inconsistent information that caused this issue.

**Comment by murarth** [comment]
I've submitted PR #1252 with my above described solution. Please let me know whether this addresses the issue.

**Comment by kchibisov** [comment]
@murarth Oh, I see, the main problem for me was to open a window on a `2` screen, keeping mouse on a `1` screen, however I've managed to do it in `awesomewm`, `alacritty` started with the correct dpi (it got dpi change event, but not a wrong dpi). So, you were correct about problem here.
